exports.trans = {
    Encrypt: {
        en: "Encryption of all passwords done!",
        de: "Verschlüsselung aller Passwörter!",
        ru: "Шифрование всех паролей!",
        pt: "Criptografia de todas as senhas feitas!",
        nl: "Encryptie van alle wachtwoorden!",
        fr: "Cryptage de tous les mots de passe !",
        it: "Crittografia di tutte le password fatte!",
        es: "¡Encriptación de todas las contraseñas hechas!",
        pl: "Wszystko o wszystkich hasłach zrobiono!",
        uk: "Зашифрування всіх паролів зроблено!",
        "zh-cn": "摘录所有密码!",
    },
    "Adapter restart": {
        en: "Adapter restart",
        de: "Neustart des Adapters",
        ru: "Перезагрузка адаптера",
        pt: "Reinicie o adaptador",
        nl: "Adapter herstel",
        fr: "Redémarrage de l ' adaptateur",
        it: "Riavvio dell'adattatore",
        es: "Adaptador reinicio",
        pl: "Adapter restart",
        uk: "Перезапуск адаптера",
        "zh-cn": "修补",
    },
    "No imap": {
        en: "No Host is created in the Instance Config.",
        de: "Kein Host in der Instanz Config erstellt.",
        ru: "В Instance Config не создается хозяин.",
        pt: "Nenhum Host é criado no Config de Instância.",
        nl: "Geen Host is gemaakt in het Instance Config.",
        fr: "No Host is created in the Instance Config.",
        it: "Nessun host viene creato nel Configurazione del caso.",
        es: "No Host se crea en el Config de la Instancia.",
        pl: "Nikt nie został utworzony w Konwencie Instancyjnym.",
        uk: "Ні Хост створюється в Конфігурації Інструкції.",
        "zh-cn": "决不成立旅。.",
    },
    catch: {
        en: "catch %s",
        de: "catch %s",
        ru: "catch %s",
        pt: "catch %s",
        nl: "catch %s",
        fr: "catch %s",
        it: "catch %s",
        es: "catch %s",
        pl: "catch %s",
        uk: "catch %s",
        "zh-cn": "catch %s",
    },
    try: {
        en: "try %s",
        de: "try %s",
        ru: "try %s",
        pt: "try %s",
        nl: "try %s",
        fr: "try %s",
        it: "try %s",
        es: "try %s",
        pl: "try %s",
        uk: "try %s",
        "zh-cn": "try %s",
    },
    "Change common": {
        en: "Change common %s",
        de: "Change common %s",
        ru: "Change common %s",
        pt: "Change common %s",
        nl: "Change common %s",
        fr: "Change common %s",
        it: "Change common %s",
        es: "Change common %s",
        pl: "Change common %s",
        uk: "Change common %s",
        "zh-cn": "Change common %s",
    },
    Datapoint: {
        en: "Datapoint: %s",
        de: "Datapoint: %s",
        ru: "Datapoint: %s",
        pt: "Datapoint: %s",
        nl: "Datapoint: %s",
        fr: "Datapoint: %s",
        it: "Datapoint: %s",
        es: "Datapoint: %s",
        pl: "Datapoint: %s",
        uk: "Призначення: %s",
        "zh-cn": "数据点: %s",
    },
    "Reload emails": {
        en: "Reload emails (e.g. after HTML changes)",
        de: "E-Mails neu laden (z.B. nach HTML-Änderungen)",
        ru: "Перезагрузите электронные письма (например, после изменения HTML)",
        pt: "Recarregar e-mails (por exemplo, após alterações HTML)",
        nl: "Herlaad e-mails (e.g na HTML veranderingen)",
        fr: "Recharger les courriels (p. ex. après les modifications HTML)",
        it: "Ricaricare le email (ad esempio dopo le modifiche HTML)",
        es: "Recargar correos electrónicos (por ejemplo después de cambios HTML)",
        pl: "Reload emails (np. po zmianach HTML)",
        uk: "Перевантаження електронних листів (наприклад, після зміни HTML)",
        "zh-cn": "有效电子邮件(例如HTML变动后)",
    },
    Command: {
        en: "Command: %s",
        de: "Befehl: %s",
        ru: "Команда: %s",
        pt: "Comando: %s",
        nl: "Commando: %s",
        fr: "Commandant: %s",
        it: "Comando: %s",
        es: "Comando: %s",
        pl: "Dowództwo: %s",
        uk: "Про компанію: %s",
        "zh-cn": "指挥: %s",
    },
    "Missing quality": {
        en: "Missing quality %s.",
        de: "Fehlende Qualität %s.",
        ru: "Отсутствие качества %s.",
        pt: "Qualidade de falta %s.",
        nl: "Vermiste kwaliteit %s.",
        fr: "La qualité manquante %s.",
        it: "Qualità mancante %s.",
        es: "Falta la calidad %s.",
        pl: "Jakość %s.",
        uk: "Якість промивання %s.",
        "zh-cn": "发布质量%s.",
    },
    Found: {
        en: "Found: %s",
        de: "Gefunden: %s",
        ru: "Найдено: %s",
        pt: "Encontrei: %s",
        nl: "Gevonden: %s",
        fr: "Trouvé: %s",
        it: "Trovato: %s",
        es: "Encontrado: %s",
        pl: "Założyciel: %s",
        uk: "Знайдено: %s",
        "zh-cn": "创始人: %s",
    },
    "Not found": {
        en: "Not found: %s",
        de: "Nicht gefunden: %s",
        ru: "Не найдено: %s",
        pt: "Não encontrado: %s",
        nl: "Niet gevonden: %s",
        fr: "Non trouvé: %s",
        it: "Non trovato: %s",
        es: "No se encontró: %s",
        pl: "Nie odnaleziony: %s",
        uk: "Не знайдено: %s",
        "zh-cn": "未发现: %s",
    },
    qualitiy: {
        en: "Datapoints Quality",
        de: "Datenpunkte Qualität",
        ru: "Качество точек данных",
        pt: "Qualidade dos Datapoints",
        nl: "Quality",
        fr: "Datapoints Qualité",
        it: "Qualità dei datapoint",
        es: "Datapoints Quality",
        pl: "Jakość danych",
        uk: "Якість точок даних",
        "zh-cn": "数据点 质量",
    },
    "Data point quality is cleaned up": {
        en: "Data point quality is cleaned up.",
        de: "Datenpunkt Qualität wird bereinigt.",
        ru: "Качество точки данных очищается.",
        pt: "A qualidade do ponto de dados é limpa.",
        nl: "Datapunt kwaliteit is opgeruimd.",
        fr: "La qualité du point de données est nettoyée.",
        it: "La qualità del punto di dati viene ripulita.",
        es: "La calidad del punto de datos está limpiada.",
        pl: "Jakość danych jest oczyszczona.",
        uk: "Якість точки даних очищається.",
        "zh-cn": "数据点质量是清洁的。.",
    },
    "no host": {
        en: "No host entered in the instance!",
        de: "Kein Host in der Instanz eingegeben!",
        ru: "Не вошел в пример!",
        pt: "Nenhum anfitrião entrou na instância!",
        nl: "Geen gastheer in het voordeel!",
        fr: "Aucun hôte n'est entré dans l'instance !",
        it: "Nessun ospite è entrato nell'istanza!",
        es: "¡Ningún anfitrión entró en el caso!",
        pl: "Nikt nie wszedł w to miejsce!",
        uk: "Немає введеного в екземпляр!",
        "zh-cn": "无主机!",
    },
    "Start new search": {
        en: "Start new search",
        de: "Neue Suche starten",
        ru: "Начать новый поиск",
        pt: "Iniciar nova pesquisa",
        nl: "Begin met zoeken",
        fr: "Commencer une nouvelle recherche",
        it: "Avviare nuova ricerca",
        es: "Iniciar nueva búsqueda",
        pl: "Rozpoczęcie poszukiwań",
        uk: "Початок пошуку",
        "zh-cn": "B. 新的搜查",
    },
    "Show maximum emails": {
        en: "Show maximum emails",
        de: "Maximale E-Mails anzeigen",
        ru: "Показать максимум писем",
        pt: "Mostrar e-mails máximos",
        nl: "Toon maximale e-mails",
        fr: "Afficher les emails maximum",
        it: "Mostra le e-mail massime",
        es: "Mostrar correos electrónicos máximos",
        pl: "Show maximum e-mail",
        uk: "Показати максимальні електронні листи",
        "zh-cn": "最高电子邮件",
    },
    criteria: {
        en: "criteria",
        de: "kriterien",
        ru: "критерия",
        pt: "critérios",
        nl: "criteria",
        fr: "critères",
        it: "criteri",
        es: "criterios",
        pl: "kryteria",
        uk: "критерії",
        "zh-cn": "标准",
    },
    change_attribut: {
        en: "Attribute %s is changed for device %s.",
        de: "Das Attribut %s wird für das Gerät %s geändert.",
        ru: "Атрибут %s изменен на устройство %s.",
        pt: "Atributo %s é alterado para dispositivo %s.",
        nl: "Attribute %s is veranderd voor apparaat %s.",
        fr: "Attribute %s est modifié pour le dispositif %s.",
        it: "Attributo %s è cambiato per il dispositivo %s.",
        es: "El atributo %s se cambia para el dispositivo %s.",
        pl: "Atrybut %s został zmieniony na urządzenie %s.",
        uk: "Атрибут %s змінено для пристрою %s.",
        "zh-cn": "对装置%s的降解量%s。.",
    },
    "missing port": {
        en: "No port entered in the instance. The standard port 993 is used.",
        de: "Kein Port in der Instanz eingegeben. Der Standardport 993 wird verwendet.",
        ru: "Нет порта, введенного в пример. Используется стандартный порт 993.",
        pt: "Nenhuma porta entrou na instância. A porta padrão 993 é usada.",
        nl: "Geen haven in het voordeel. De standaard haven 993 is gebruikt.",
        fr: "Aucun port n'est entré dans l'instance. Le port standard 993 est utilisé.",
        it: "Nessuna porta è entrata nell'istanza. Viene utilizzata la porta standard 993.",
        es: "Ningún puerto entró en la instancia. El puerto estándar 993 se utiliza.",
        pl: "Na przykład nie wszedł żaden port. Zastosowano standardowy port 993.",
        uk: "Немає порту, введених в екземплярі. Використовується стандартний порт 993.",
        "zh-cn": "例如,没有港口进入。 使用标准港口993。.",
    },
    "missing username": {
        en: "No username entered in the instance.",
        de: "Kein Benutzername in der Instanz eingegeben.",
        ru: "Нет имени пользователя, введенного в пример.",
        pt: "Nenhum nome de usuário entrou na instância.",
        nl: "Geen gebruikersnaam ingevoerd in het geval.",
        fr: "Aucun nom d'utilisateur n'est entré dans l'instance.",
        it: "Nessun nome utente inserito nell'istanza.",
        es: "Ningún nombre de usuario entró en la instancia.",
        pl: "W tym przypadku nie wprowadzono nazwy użytkownika.",
        uk: "Немає імені користувача, введених в екземпляр.",
        "zh-cn": "例如没有用户名称。.",
    },
    "missing password": {
        en: "No password entered in the instance.",
        de: "Kein Passwort in der Instanz eingegeben.",
        ru: "Пароль не введен в примере.",
        pt: "Nenhuma senha inserida na instância.",
        nl: "Geen wachtwoord ingevoerd in het geval.",
        fr: "Aucun mot de passe n'est entré dans l'instance.",
        it: "Nessuna password inserita nell'istanza.",
        es: "No hay contraseña en la instancia.",
        pl: "Na przykład nie wprowadzono hasła.",
        uk: "Немає пароля в екземплярі.",
        "zh-cn": "例如没有密码。.",
    },
    "create device": {
        en: "Create folder for device %s.",
        de: "Ordner für das Gerät %s erstellen.",
        ru: "Создать папку для устройства %s.",
        pt: "Criar pasta para dispositivo %s.",
        nl: "Creëer de map voor apparaat %s.",
        fr: "Créer un dossier pour le périphérique %s.",
        it: "Crea cartella per dispositivo %s.",
        es: "Crear carpeta para el dispositivo %s.",
        pl: "Fałszerstwo dla urządzenia %s.",
        uk: "Створіть папку для пристрою %s.",
        "zh-cn": "D. 制造装置的载体 %s.",
    },
    "create mailbox folder": {
        en: "New mailbox folder create (e.g. INBOX.imap)",
        de: "Neue Mailbox-Ordner erstellen (z.B. INBOX.imap)",
        ru: "Создание новой папки почтового ящика (например, INBOX.imap)",
        pt: "Nova pasta de caixa de correio criar (por exemplo, INBOX.imap)",
        nl: "Nieuwe mailboxmap aanmaken (bijv. INBOX.imap)",
        fr: "Création d'un nouveau dossier boîte aux lettres (par exemple INBOX.imap)",
        it: "Nuova cartella casella di posta creare (ad esempio INBOX.imap)",
        es: "Nueva carpeta del buzón crear (por ejemplo, INBOX.imap)",
        pl: "Utwórz nowy folder pocztowy (np. INBOX.imap)",
        uk: "Нова папка поштових скриньок (наприклад, INBOX.imap)",
        "zh-cn": "新建邮箱文件夹( 如 INBOX. imap)",
    },
    "delete mailbox folder": {
        en: "New mailbox folder delete (e.g. INBOX.imap)",
        de: "Neue Mailbox-Ordner löschen (z.B. INBOX.imap)",
        ru: "Удалить папку нового почтового ящика (например, INBOX.imap)",
        pt: "Nova pasta de caixa de correio excluir (por exemplo, INBOX.imap)",
        nl: "Nieuwe mailboxmap verwijderen (bv. INBOX.imap)",
        fr: "Supprimer un nouveau dossier de boîte aux lettres (par exemple INBOX.imap)",
        it: "Nuova cartella casella di posta elimina (ad esempio INBOX.imap)",
        es: "Nueva carpeta de correo eliminar (por ejemplo, INBOX.imap)",
        pl: "Usuwanie nowego folderu pocztowego (np. INBOX.imap)",
        uk: "English, Українська, Français..",
        "zh-cn": "新建邮箱文件夹删除( 如 INBOX. imap)",
    },
    "Status Host": {
        en: "Status Host",
        de: "Status Host",
        ru: "Статус Host",
        pt: "Anfitrião de status",
        nl: "Status Hostus",
        fr: "État hôte",
        it: "Stato Host",
        es: "Status Host",
        pl: "Status Host",
        uk: "Статус на сервери",
        "zh-cn": "身份",
    },
    Unknown: {
        en: "Unknown",
        de: "Unbekannt",
        ru: "Неизвестные",
        pt: "Desconhecido",
        nl: "Onbekend",
        fr: "Inconnu",
        it: "Sconosciuto",
        es: "Desconocida",
        pl: "Nieznany",
        uk: "Невідомо",
        "zh-cn": "目 录",
    },
    connection: {
        en: "Connected with %s",
        de: "Mit %s verbunden",
        ru: "Подключено с %s",
        pt: "Conectado com %s",
        nl: "Verbinding met %s",
        fr: "Connecté avec %s",
        it: "Collegato con %s",
        es: "Conectado con %s",
        pl: "Połączenie z %s",
        uk: "Підключення %s",
        "zh-cn": "第%s条",
    },
    mailbox: {
        en: "mailbox %s",
        de: "Postfach %s",
        ru: "почтовый ящик %s",
        pt: "caixa de correio %s",
        nl: "brievenbus %s",
        fr: "mailbox %s",
        it: "casella postale %s",
        es: "buzón de correo %s",
        pl: "mailbox %s",
        uk: "поштова скринька %s",
        "zh-cn": "邮件箱 %s",
    },
    disconnected: {
        en: "IMAP connection lost from %s - %s.",
        de: "IMAP-Verbindung verloren von %s - %s.",
        ru: "IMAP соединение потеряно с %s - %s.",
        pt: "Ligação IMAP perdida de %s - %s.",
        nl: "IMAP verbinding verloren van %s - %s.",
        fr: "Connexion IMAP perdue à partir de %s - %s.",
        it: "Connessione IMAP persa dal %s - %s.",
        es: "Conexión IMAP perdida de %s - %s.",
        pl: "Związek IMAP stracił z %s - %s.",
        uk: "З'єднання IMAP від %s - %s.",
        "zh-cn": "IMAP 损失%s - %s.",
    },
    Error: {
        en: "Error to Host %s - %s.",
        de: "Fehler bei Host %s - %s.",
        ru: "Ошибка для хоста %s - %s.",
        pt: "Erro ao Host %s - %s.",
        nl: "Error naar Host %s - %s.",
        fr: "Erreur d'accueil %s - %s.",
        it: "Errore a Host %s - %s.",
        es: "Error para acoger %s - %s.",
        pl: "Wiersz do domu %s - %s.",
        uk: "Помилка для хосту %s - %s.",
        "zh-cn": "旅舍。 %s - %s.",
    },
    Mail: {
        en: "Mail %s - %s",
        de: "Post %s - %s",
        ru: "Почта %s - %s",
        pt: "Correio %s - %s",
        nl: "Post %s - %s",
        fr: "Mail %s - %s",
        it: "Mail %s - %s",
        es: "Mail %s - %s",
        pl: "Mail %s - %s",
        uk: "Почати %s - %s",
        "zh-cn": "邮件 %s - %s",
    },
    Attributes: {
        en: "Attributes %s - %s",
        de: "Attribute %s - %s",
        ru: "Атрибуты %s - %s",
        pt: "Atributos %s - %s",
        nl: "Attributen %s - %s",
        fr: "Attributs %s - %s",
        it: "Attributi %s - %s",
        es: "Atributos %s - %s",
        pl: "Attribute %s - %s",
        uk: "Атрибути %s - %s",
        "zh-cn": "导 言 %s - %s.",
    },
    Sequense: {
        en: "Sequense number %s - %s",
        de: "Sequenznummer %s - %s",
        ru: "Sequense номер %s - %s",
        pt: "Número de perguntas %s - %s",
        nl: "Vertaling: %s - %s",
        fr: "Numéro de séquence %s - %s",
        it: "Numero di sequenze %s - %s",
        es: "Número secuencial %s - %s",
        pl: "Liczba sekwencjonalna %s - %s",
        uk: "Кількість місць %s - %s",
        "zh-cn": "犯罪人数 %s - %s",
    },
    Info: {
        en: "Info %s - %s",
        de: "Info %s - %s",
        ru: "Информация %s - %s",
        pt: "Info %s - %s",
        nl: "Info %s - %s",
        fr: "Info %s - %s",
        it: "Info %s - %s",
        es: "Info %s - %s",
        pl: "Info %s - %s",
        uk: "Новини %s - %s",
        "zh-cn": "信息 %s - %s",
    },
    Attachment: {
        en: "Attachment %s - %s",
        de: "Anlage %s - %s",
        ru: "Приспособление %s - %s",
        pt: "Anexo %s - %s",
        nl: "Attach %s - %s",
        fr: "Attachment %s - %s",
        it: "Attaccamento %s - %s",
        es: "Adjunción %s - %s",
        pl: "Attachment %s - %s",
        uk: "Пристрої %s - %s",
        "zh-cn": "附录 %s - %s",
    },
    "Mail content": {
        en: "eMail content",
        de: "eMail Inhalt",
        ru: "eMail контент",
        pt: "conteúdo eMail",
        nl: "eMail tevreden",
        fr: "contenu eMail",
        it: "contenuto eMail",
        es: "eMail content",
        pl: "treści eMail",
        uk: "зміст електронної пошти",
        "zh-cn": "e Mail内容",
    },
    "e-Mail": {
        en: "e-Mail",
        de: "e-Mail",
        ru: "e-mail",
        pt: "e-mail",
        nl: "e-Mail",
        fr: "e-Mail",
        it: "e-mail",
        es: "e-Mail",
        pl: "e-Mail",
        uk: "електронна пошта",
        "zh-cn": "e-Mail",
    },
    Receive: {
        en: "Receive",
        de: "Empfang",
        ru: "Получить",
        pt: "Receber",
        nl: "Ontvangen",
        fr: "Reçu",
        it: "Ricevi",
        es: "Recibido",
        pl: "Received",
        uk: "Отримати",
        "zh-cn": "收 款",
    },
    "e-Mail Subject": {
        en: "e-Mail Subject",
        de: "e-Mail Betreff",
        ru: "e-Mail Тема",
        pt: "e-Mail Assunto",
        nl: "e-Mail Subject",
        fr: "sujet e-Mail",
        it: "e-Mail Soggetto",
        es: "e-Mail Subject",
        pl: "e-Mail Subject (ang.)",
        uk: "тема електронної пошти",
        "zh-cn": "e. 主题",
    },
    To: {
        en: "e-Mail To",
        de: "e-Mail an",
        ru: "e-Mail на",
        pt: "e-mail para",
        nl: "e-Mail To",
        fr: "e-Mail To",
        it: "e-mail a",
        es: "e-Mail To",
        pl: "e-mail",
        uk: "електронна пошта",
        "zh-cn": "e-Mail To",
    },
    From: {
        en: "e-Mail From",
        de: "e-Mail Von",
        ru: "e-Mail От",
        pt: "e-mail de",
        nl: "e-Mail van",
        fr: "e-Mail de",
        it: "e-mail da",
        es: "e-Mail From",
        pl: "e-Mail From",
        uk: "електронна пошта",
        "zh-cn": "e-Mail",
    },
    Text: {
        en: "e-Mail Text",
        de: "e-Mail Text",
        ru: "e-Mail Текст",
        pt: "texto e-mail",
        nl: "e-Mail Text",
        fr: "texte e-mail",
        it: "testo e-mail",
        es: "e-Mail Text",
        pl: "tekst elektroniczny",
        uk: "електронна пошта",
        "zh-cn": "电子案文",
    },
    TextHTML: {
        en: "e-Mail Text as HTML",
        de: "e-Mail Text als HTML",
        ru: "e-Mail Текст как HTML",
        pt: "e-Mail Texto como HTML",
        nl: "e-Mail Tex als HTML",
        fr: "texte e-mail en HTML",
        it: "testo e-mail come HTML",
        es: "texto electrónico como HTML",
        pl: "tekst e-Mail jako HTML",
        uk: "javaScript licenses API Веб-сайт Go1.13.8",
        "zh-cn": "e-Mail文本作为HTML",
    },
    Flag: {
        en: "Flags",
        de: "Flaggen",
        ru: "Флаги",
        pt: "Bandeiras",
        nl: "Flags",
        fr: "Drapeaux",
        it: "Bandiere",
        es: "Banderas",
        pl: "Flaga",
        uk: "Прапори",
        "zh-cn": "Flags",
    },
    UID: {
        en: "UID",
        de: "UID",
        ru: "УИД",
        pt: "UID",
        nl: "_",
        fr: "UID",
        it: "UTILIZZO",
        es: "UID",
        pl: "UID",
        uk: "УВІЙТИ",
        "zh-cn": "国际组织",
    },
    SEQ: {
        en: "Sequence number",
        de: "Sequenznummer",
        ru: "Номер последовательности",
        pt: "Número de sequência",
        nl: "Vertaling:",
        fr: "Numéro de séquence",
        it: "Numero di sequenza",
        es: "Número de secuencia",
        pl: "Liczba sekwencjonacyjna",
        uk: "Кількість місць",
        "zh-cn": "离职人数",
    },
    "Apply selection": {
        en: "Apply selection",
        de: "Auswahl anwenden",
        ru: "Подать заявку",
        pt: "Aplicar seleção",
        nl: "Applicatie",
        fr: "Appliquer la sélection",
        it: "Applicare la selezione",
        es: "Selección de aplicaciones",
        pl: "Wybór",
        uk: "Підбір заявок",
        "zh-cn": "评 注",
    },
    "No UID specified": {
        en: "No UID specified",
        de: "Keine UID angegeben",
        ru: "Не указано UID",
        pt: "Nenhum UID especificado",
        nl: "Geen UID gespecificeerd",
        fr: "No UID specified",
        it: "Nessun UID specificato",
        es: "No UID especificado",
        pl: "Niewyjaśnione",
        uk: "Ні вказаний",
        "zh-cn": "未具体说明",
    },
    "No folder selected": {
        en: "No folder selected",
        de: "Kein Ordner ausgewählt",
        ru: "Не выбрана папка",
        pt: "Nenhuma pasta selecionada",
        nl: "Geen map geselecteerd",
        fr: "Pas de dossier sélectionné",
        it: "Nessuna cartella selezionata",
        es: "No hay carpeta seleccionada",
        pl: "Nie wybrano",
        uk: "Немає вибраної папки",
        "zh-cn": "未选定会议",
    },
    "move e-mail": {
        en: "move e-mail",
        de: "e-mail verschieben",
        ru: "переместить e-mail",
        pt: "mover e-mail",
        nl: "verplaats e-mail",
        fr: "e-mail",
        it: "spostare e-mail",
        es: "mover correo electrónico",
        pl: "e-mail",
        uk: "перемістити e-mail",
        "zh-cn": "电子邮件",
    },
    capability: {
        en: "capability",
        de: "Fähigkeit",
        ru: "возможность",
        pt: "capacidade",
        nl: "",
        fr: "capacité",
        it: "capacità",
        es: "capacidad",
        pl: "możliwości",
        uk: "можливість",
        "zh-cn": "能力",
    },
    Storage_value: {
        en: "Storage %s - %s",
        de: "Lagerung %s - %s",
        ru: "Хранение %s - %s",
        pt: "Armazenamento %s - %s",
        nl: "Vertaling: %s - %s",
        fr: "Stockage %s - %s",
        it: "Stoccaggio %s - %s",
        es: "Almacenamiento %s - %s",
        pl: "Storage %s - %s",
        uk: "Склад %s - %s",
        "zh-cn": "导 言 %s - %s",
    },
    Storage: {
        en: "Storage",
        de: "Lagerung",
        ru: "Хранение",
        pt: "Armazenamento",
        nl: "Vertaling:",
        fr: "Stockage",
        it: "Stoccaggio",
        es: "Almacenamiento",
        pl: "Storage",
        uk: "Склад",
        "zh-cn": "导 言",
    },
    Limit: {
        en: "Limit",
        de: "Begrenzung",
        ru: "Лимит",
        pt: "Limitação",
        nl: "Limit",
        fr: "Limite",
        it: "Limite",
        es: "Límite",
        pl: "Limit",
        uk: "Ліміт",
        "zh-cn": "限制",
    },
    Usage: {
        en: "Usage",
        de: "Verwendung",
        ru: "Использование",
        pt: "Uso",
        nl: "Vertaling:",
        fr: "Utilisation",
        it: "Utilizzo",
        es: "Usage",
        pl: "Usługa",
        uk: "Проживання",
        "zh-cn": "乌 尔",
    },
    "All support": {
        en: "All support",
        de: "Alle Unterstützung",
        ru: "Вся поддержка",
        pt: "Todos os suportes",
        nl: "Alle steun",
        fr: "Tous les appuis",
        it: "Tutto il supporto",
        es: "Todo apoyo",
        pl: "Wsparcie",
        uk: "Підтримка",
        "zh-cn": "所有支助",
    },
    "Is supported": {
        en: "Is %s supported?",
        de: "Wird %s unterstützt?",
        ru: "Поддерживается %s?",
        pt: "O %s é suportado?",
        nl: "Is %s ondersteund?",
        fr: "Est-ce que %s sont pris en charge?",
        it: "%s è supportato?",
        es: "¿Está respaldada %s?",
        pl: "Wspiera się %s osób?",
        uk: "Чи підтримує %s?",
        "zh-cn": "是否支持%s?",
    },
    "move or copy": {
        en: "copy/paste",
        de: "kopie/paste",
        ru: "копия/вкус",
        pt: "cópia/paste",
        nl: "kopie/invoegen",
        fr: "copier/coller",
        it: "copia/incolla",
        es: "copia/paste",
        pl: "copy/pastie",
        uk: "копія/паста",
        "zh-cn": "附 件",
    },
    "Flag action": {
        en: "Flag action",
        de: "Flaggenaktion",
        ru: "Флаг действие",
        pt: "Ação da bandeira",
        nl: "Flag actie",
        fr: "Action du drapeau",
        it: "Azione della bandiera",
        es: "Acción de bandera",
        pl: "Flaga",
        uk: "Прапор дії",
        "zh-cn": "滞后行动",
    },
    "copy e-mail to folder": {
        en: "copy e-mail to folder",
        de: "e-mail in den Ordner kopieren",
        ru: "скопировать e-mail в папку",
        pt: "copiar e-mail para pasta",
        nl: "e-mail naar map",
        fr: "copier e-mail dans le dossier",
        it: "copiare e-mail nella cartella",
        es: "copiar correo electrónico a la carpeta",
        pl: "e-mail do foldera",
        uk: "копіювання електронної пошти в папку",
        "zh-cn": "电子邮件:der",
    },
    copy: {
        en: "copy",
        de: "kopie",
        ru: "копия",
        pt: "cópia",
        nl: "kopie",
        fr: "copie",
        it: "copia",
        es: "copia",
        pl: "copy",
        uk: "копія",
        "zh-cn": "附 件",
    },
    move: {
        en: "move",
        de: "verschiebe",
        ru: "двигаться",
        pt: "mexam-se",
        nl: "bewegen",
        fr: "bouge",
        it: "muoversi",
        es: "muévanse",
        pl: "ruch",
        uk: "увійти",
        "zh-cn": "行动",
    },
    "Select target folder": {
        en: "Select target folder",
        de: "Zielordner auswählen",
        ru: "Выберите целевую папку",
        pt: "Selecione a pasta de destino",
        nl: "Select doelwit map",
        fr: "Sélectionnez le dossier cible",
        it: "Selezionare la cartella di destinazione",
        es: "Seleccione la carpeta de destino",
        pl: "Select target folder",
        uk: "Виберіть папку цілі",
        "zh-cn": "D. 选 定",
    },
    SIZE: {
        en: "e-Mail size",
        de: "e-Mail Größe",
        ru: "e-Mail размер",
        pt: "tamanho e-mail",
        nl: "e-Mail maat",
        fr: "taille e-Mail",
        it: "formato e-Mail",
        es: "tamaño e-mail",
        pl: "rozmiary e-Mail",
        uk: "розмір електронної пошти",
        "zh-cn": "e-Mail大小",
    },
    "total e-mails": {
        en: "Total e-mails.",
        de: "E-Mails insgesamt.",
        ru: "Полные электронные письма.",
        pt: "Total de e-mails.",
        nl: "Totale e-mails.",
        fr: "Total des e-mails.",
        it: "E-mail totali.",
        es: "E-mails totales.",
        pl: "Total e-mail (ang.).",
        uk: "Всього електронних листів.",
        "zh-cn": "电子邮件总数。.",
    },
    "create mails": {
        en: "Create e-mails for device %s.",
        de: "E-Mails für Gerät %s erstellen.",
        ru: "Создание электронных писем для устройства %s.",
        pt: "Criar e-mails para dispositivo %s.",
        nl: "Creëer e-mails voor apparaat %s.",
        fr: "Créer des e-mails pour le périphérique %s.",
        it: "Creare e-mail per il dispositivo %s.",
        es: "Crear correos electrónicos para el dispositivo %s.",
        pl: "Spis e-mail dla urządzenia %s.",
        uk: "Створення електронних листів для пристрою %s.",
        "zh-cn": "D. 为装置设立电子邮件 %s.",
    },
    "IMAP check start": {
        en: "IMAP check start.",
        de: "IMAP Check Start.",
        ru: "IMAP check старт.",
        pt: "Início de verificação IMAP.",
        nl: "IMAP check start.",
        fr: "Commencez le contrôle IMAP.",
        it: "Inizio controllo IMAP.",
        es: "Comienza a revisar IMAP.",
        pl: "Rozpoczyna się IMAP.",
        uk: "Запуск перевірки IMAP.",
        "zh-cn": "IMAP检查开始。.",
    },
    "Found data point": {
        en: "Found data point: %s",
        de: "Gefundener Datenpunkt: %s",
        ru: "Найдена точка данных: %s",
        pt: "Ponto de dados encontrado: %s",
        nl: "Ik vond data punt: %s",
        fr: "Point de données trouvé: %s",
        it: "Data point trovato: %s",
        es: "Punto de datos encontrado: %s",
        pl: "Ustanowiony punkt danych: %s",
        uk: "Знайдено точку даних: %s",
        "zh-cn": "丰数据点。: %s",
    },
    "Deleted data point": {
        en: "Data point %s is deleted.",
        de: "Der Datenpunkt %s wird gelöscht.",
        ru: "Точка данных %s удалена.",
        pt: "O ponto de dados %s é excluído.",
        nl: "Data punt %s is gewist.",
        fr: "Le point de données %s est supprimé.",
        it: "Il punto di dati %s viene cancellato.",
        es: "Se elimina el punto de datos %s.",
        pl: "Odcinek %s został usunięty.",
        uk: "Видалено точку даних %s.",
        "zh-cn": "数据点%s被删除。.",
    },
    "check mailfolder": {
        en: "Checking the mail folders for the device %s.",
        de: "Überprüfen der Mail-Ordner für das Gerät %s.",
        ru: "Проверка папок почты для устройства %s.",
        pt: "Verificando as pastas de correio para o dispositivo %s.",
        nl: "Controleer de postplatformers voor het apparaat %s.",
        fr: "Vérification des dossiers de courrier pour l'appareil %s.",
        it: "Controllo delle cartelle di posta per il dispositivo %s.",
        es: "Revisando las carpetas de correo para el dispositivo %s.",
        pl: "Wykorzystując foldery pocztowe dla urządzenia %s.",
        uk: "Перевірка папок пошти для пристрою %s.",
        "zh-cn": "检查装置的邮件编号%s.",
    },
    "Delete folder": {
        en: "Folder %s1 will be deleted.",
        de: "Der Ordner %s1 wird gelöscht.",
        ru: "Папка %s1 будет удалена.",
        pt: "A pasta %s1 será excluída.",
        nl: "Folder %s1 wordt verwijderd.",
        fr: "Le dossier %s1 sera supprimé.",
        it: "La cartella %s1 verrà cancellata.",
        es: "Se eliminará la carpeta %s1.",
        pl: "Z tego powodu Folder %s1 został usunięty.",
        uk: "Складаний %s1 буде видалено.",
        "zh-cn": "将会删除%s1人。.",
    },
    Remote: {
        en: "Remote",
        de: "Fernbedienung",
        ru: "Дистанционное",
        pt: "Remoto",
        nl: "Verwijder",
        fr: "Télécommande",
        it: "Telecomando",
        es: "Remoto",
        pl: "Remote",
        uk: "Відправити",
        "zh-cn": "遥感",
    },
    HTML: {
        en: "HTML settings",
        de: "HTML-Einstellungen",
        ru: "HTML настройки",
        pt: "Configurações HTML",
        nl: "HTML settings",
        fr: "Paramètres HTML",
        it: "Impostazioni HTML",
        es: "Configuración HTML",
        pl: "HTML settings",
        uk: "Налаштування HTML",
        "zh-cn": "HTML环境",
    },
    "Start Delete folder": {
        en: "Cleaning of mail folders from device %s is started.",
        de: "Die Reinigung von Mail-Ordnern vom Gerät %s wird gestartet.",
        ru: "Начата очистка почтовых папок с устройства %s.",
        pt: "A limpeza de pastas de correio do dispositivo %s é iniciada.",
        nl: "Het schoonmaken van postvouders van apparaat %s is begonnen.",
        fr: "Le nettoyage des dossiers de courrier de l'appareil %s est commencé.",
        it: "La pulizia delle cartelle di posta dal dispositivo %s è iniziata.",
        es: "Se inicia la limpieza de carpetas de correo desde el dispositivo %s.",
        pl: "Rozpoczęto montaż folderów pocztowych z urządzenia %s.",
        uk: "Розпочато очищення папок пошти з пристрою %s.",
        "zh-cn": "已开始从装置%s中抽调邮件。.",
    },
    "Stop Delete folder": {
        en: "Cleaning of mail folders from device %s is stopped.",
        de: "Die Bereinigung von Mail-Ordnern vom Gerät %s wird gestoppt.",
        ru: "Очистка почтовых папок с устройства %s прекращена.",
        pt: "A limpeza de pastas de correio do dispositivo %s é interrompida.",
        nl: "Het schoonmaken van postvouders van apparaat %s is gestopt.",
        fr: "Le nettoyage des dossiers de courrier du périphérique %s est arrêté.",
        it: "La pulizia delle cartelle di posta dal dispositivo %s è interrotta.",
        es: "Se detiene la limpieza de carpetas de correo desde el dispositivo %s.",
        pl: "Zatrzymanie folderów pocztowych z urządzeniem %s.",
        uk: "Прибирання папок пошти з пристрою %s припиняється.",
        "zh-cn": "停止从装置%s中抽调邮件。.",
    },
    "create remote": {
        en: "Remote folder is created for device %s.",
        de: "Für das Gerät %s wird ein Remote-Ordner erstellt.",
        ru: "Удаленная папка создана для устройства %s.",
        pt: "A pasta remota é criada para o dispositivo %s.",
        nl: "Verwijdervouder is gemaakt voor apparaat %s.",
        fr: "Le dossier distant est créé pour le périphérique %s.",
        it: "La cartella remota è creata per il dispositivo %s.",
        es: "La carpeta remota se crea para el dispositivo %s.",
        pl: "Zaprojektowany dla urządzenia %s.",
        uk: "Віддалена папка створена для пристрою %s.",
        "zh-cn": "用于装置%s的遥感载体.",
    },
    body_background: {
        en: "General background",
        de: "Allgemeiner Hintergrund",
        ru: "Общий фон",
        pt: "Fundo geral",
        nl: "Generaal",
        fr: "Généralités",
        it: "Sfondo generale",
        es: "Antecedentes generales",
        pl: "Strona główna",
        uk: "Загальний фон",
        "zh-cn": "A. 一般背景",
    },
    p_tag_text_align: {
        en: "TAG (p) text align.",
        de: "TAG (p) Text ausrichten.",
        ru: "TAG (p) текст выравнивается.",
        pt: "TAG (p) alinhamento de texto.",
        nl: "TAG (p) Smsalign.",
        fr: "TAG (p) texte aligné.",
        it: "TAG (p) testo allineare.",
        es: "TAG (p) text align.",
        pl: "Tekst TAG (p) dopasował się do tekstu.",
        uk: "TAG (p) вирівнювання тексту.",
        "zh-cn": "TAG(p)案文一致.",
    },
    td_tag_cell: {
        en: "TAG (td) distance cell",
        de: "TAG (td) Entfernungszelle",
        ru: "TAG (td) расстояние клетки",
        pt: "TAG (td) célula de distância",
        nl: "TAG (td) afstand",
        fr: "TAG (td) distance cell",
        it: "Cella di distanza TAG (td)",
        es: "TAG célula de distancia (td)",
        pl: "TAG (td) distance cell",
        uk: "TAG (td) дистанції",
        "zh-cn": "TAG (td) 远距离牢房",
    },
    td_tag_border_color: {
        en: "TAG (td) border color.",
        de: "TAG (td) Randfarbe.",
        ru: "TAG (td) цвет границы.",
        pt: "TAG (td) cor da borda.",
        nl: "TAG (td) grenskleur.",
        fr: "TAG (td) couleur frontière.",
        it: "TAG (td) colore di confine.",
        es: "TAG (td) color de frontera.",
        pl: "TAG (td) kolor graniczny.",
        uk: "TAG (td) бордюрний колір.",
        "zh-cn": "TAG td边界色。.",
    },
    td_tag_border_right: {
        en: "TAG (td) border right.",
        de: "TAG (td) Grenze rechts.",
        ru: "TAG (td) граница право.",
        pt: "TAG (td) fronteira direita.",
        nl: "TAG (td) grensrecht.",
        fr: "TAG (td) frontière droite.",
        it: "TAG (td) frontiera destra.",
        es: "TAG (td) border right.",
        pl: "TAG (td) rację graniczną.",
        uk: "TAG (td) кордон прямо.",
        "zh-cn": "TAGad边界权利。.",
    },
    td_tag_border_bottom: {
        en: "TAG (td) border bottom.",
        de: "TAG (td) Grenzboden.",
        ru: "TAG (td) граница дно.",
        pt: "TAG (td) borda inferior.",
        nl: "TAG (td) grensonder.",
        fr: "TAG (td) border bottom.",
        it: "TAG (td) bordo inferiore.",
        es: "TAG (td) borde inferior.",
        pl: "TAG (td) border (ang.).",
        uk: "TAG (td) бордовий дно.",
        "zh-cn": "TAG td边界。.",
    },
    table_tag_text_align: {
        en: "TAG (table) text align (e.g. auto or 25px 50px 75px).",
        de: "TAG (table) Text ausrichten (z.B. auto oder 25px 50px 75px.).",
        ru: "TAG (table) текст (например, авто или 25px 50px 75px.).",
        pt: "TAG (table) alinhamento de texto (por exemplo, auto ou 25px 50px 75px.).",
        nl: "TAG (table) sms-align (e.g auto of 25px 50px 75px.).",
        fr: "TAG (table) texte aligné (p. ex. auto ou 25px 50px 75px.).",
        it: "TAG (table) testo allineare (ad esempio auto o 25px 50px 75px.).",
        es: "TAG (table) texto alineado (por ejemplo auto o 25px 50px 75px.).",
        pl: "TAG (table) dopasował (np. auto lub 25 px 50 px).",
        uk: "TAG (table) текст вирівнювання (наприклад, авто або 25px 50px 75px).",
        "zh-cn": "TAG(table)案文(如汽车或25px 50px 75px).",
    },
    table_tag_width: {
        en: "TAG (table) width (e.g. auto or 100px)",
        de: "TAG (table) Breite (z.B. Auto oder 100px)",
        ru: "TAG (table) ширина (например, авто или 100px)",
        pt: "TAG (table) largura (por exemplo, auto ou 100px)",
        nl: "TAG (table) width (e.g auto of 100px)",
        fr: "TAG (table) largeur (p. ex. auto ou 100px)",
        it: "Larghezza TAG (table) (ad esempio auto o 100px)",
        es: "TAG (table) ancho (por ejemplo auto o 100px)",
        pl: "TAG (table) szerokość (np. auto lub 100 KM)",
        uk: "TAG (table) ширина (наприклад, авто або 100px)",
        "zh-cn": "TAG(table)妻子(如汽车或100px)",
    },
    table_tag_border_color: {
        en: "TAG (table) border color.",
        de: "TAG (table) Randfarbe.",
        ru: "TAG (table) цвет границы.",
        pt: "TAG (table) cor da borda.",
        nl: "TAG (table) grenskleur.",
        fr: "TAG (table) couleur frontière.",
        it: "TAG (table) colore di confine.",
        es: "TAG (table) color fronterizo.",
        pl: "TAG (table) – kolor graniczny.",
        uk: "TAG (table) бордовий колір.",
        "zh-cn": "TAG (table)个边界色。.",
    },
    table_tag_cell: {
        en: "TAG (table) distance cell",
        de: "TAG (table) Entfernungszelle",
        ru: "TAG (table) расстояние клетки",
        pt: "TAG (table) célula de distância",
        nl: "TAG (table) afstand",
        fr: "TAG (table) distance cell",
        it: "Cella di distanza TAG (table)",
        es: "TAG célula de distancia (table)",
        pl: "TAG (table) distance cell",
        uk: "TAG (table) дистанції",
        "zh-cn": "TAG(table) 远距离牢房",
    },
    td_tag_2_colums: {
        en: "TAG (td) width for the first 2 columns (e.g. auto or 100px).",
        de: "TAG (td) Breite für die ersten 2 Spalten (z.B. Auto oder 100px.).",
        ru: "TAG (td) ширина для первых 2 колонн (например, авто или 100px.).",
        pt: "TAG (td) largura para as primeiras 2 colunas (por exemplo, auto ou 100px.).",
        nl: "TAG (td) breedte voor de eerste twee kolommen (e.g auto of 100px).",
        fr: "TAG (td) largeur pour les 2 premières colonnes (p. ex. auto ou 100px.).",
        it: "Larghezza TAG (td) per le prime 2 colonne (ad esempio auto o 100px.).",
        es: "TAG (td) ancho para las primeras 2 columnas (por ejemplo auto o 100px.).",
        pl: "TAG (td) szerokości dla pierwszych dwóch kolumn (np. auto lub 100 KM).",
        uk: "TAG (td) ширина за перші 2 стовпчики (наприклад, авто або 100px).",
        "zh-cn": "TAG (td) 第一个第2栏(如汽车或100px)的妻子。.",
    },
    html_code: {
        en: "HTML code",
        de: "HTML-Code",
        ru: "HTML код",
        pt: "Código HTML",
        nl: "HTML code",
        fr: "Code HTML",
        it: "Codice HTML",
        es: "Código HTML",
        pl: "Kod HTML",
        uk: "Код HTML",
        "zh-cn": "HTML守则",
    },
    "read html": {
        en: "Read HTML code for host %s.",
        de: "HTML-Code für Host %s lesen.",
        ru: "Прочитайте HTML код для хоста %s.",
        pt: "Leia o código HTML para host %s.",
        nl: "Lees HTML code voor gastheer %s.",
        fr: "Lisez code HTML pour host %s.",
        it: "Leggi codice HTML per host %s.",
        es: "Lea código HTML para host %s.",
        pl: "Czytelnik HTML dla hosta %s.",
        uk: "Читання HTML коду для хосту %s.",
        "zh-cn": "B. 东道主的读者守则 %s.",
    },
    header_tag_border_color: {
        en: "TAG (table) header border color.",
        de: "TAG (table) Header Randfarbe.",
        ru: "TAG (table) цвет границы заголовка.",
        pt: "TAG (table) cor da borda do cabeçalho.",
        nl: "TAG (table) hoofd grenskleur.",
        fr: "TAG (table) couleur de la bordure d'en-tête.",
        it: "TAG (table) intestazione bordo colore.",
        es: "TAG (table) de color de borde de cabecera.",
        pl: "TAG (table) – kolor graniczny.",
        uk: "TAG (table) заголовок прикордонного кольору.",
        "zh-cn": "TAG (table)头邻。.",
    },
    header_border: {
        en: "TAG (table) header border.",
        de: "TAG (table) Kopfgrenze.",
        ru: "TAG (table) границы заголовка.",
        pt: "TAG (table) fronteira de cabeçalho.",
        nl: "TAG (table) hoofdgrens.",
        fr: "TAG (table) tête frontière.",
        it: "TAG (table) bordo intestazione.",
        es: "TAG (table) frontera de cabecera.",
        pl: "TAG (table) – granica głodowa.",
        uk: "TAG (table) заголовок кордону.",
        "zh-cn": "TAG (table)头寸边界。.",
    },
    header_width: {
        en: "TAG (table) header width (e.g. auto, 100% or 1080px).",
        de: "TAG (table) Kopfbreite (z.B. Auto, 100% oder 1080px.).",
        ru: "TAG (table) ширина заголовка (например, авто, 100% или 1080px.).",
        pt: "TAG (table) largura do cabeçalho (por exemplo, auto, 100% ou 1080px.).",
        nl: "TAG (table) koper width (e.g auto, 100% of 1080px).",
        fr: "Largeur d'en-tête TAG (table) (p. ex. auto, 100% ou 1080px.).",
        it: "Larghezza intestazione TAG (table) (ad esempio auto, 100% o 1080px.).",
        es: "TAG (table) ancho de cabecera (por ejemplo auto, 100% o 1080px.).",
        pl: "TAG (table) (np. auto, 100% lub 1080 KM).",
        uk: "TAG (table) ширина заголовка (наприклад, автоматичний, 100% або 1080px).",
        "zh-cn": "TAG (table) 头巾(如汽车、100%或1080px).",
    },
    header_text_color: {
        en: "TAG (table) header text color.",
        de: "TAG (table) Header Textfarbe.",
        ru: "TAG (table) цвет текста заголовка.",
        pt: "TAG (table) cor de texto de cabeçalho.",
        nl: "TAG (table) kopersleutel kleur.",
        fr: "Couleur du texte de l'en-tête TAG (table).",
        it: "TAG (table) intestazione colore del testo.",
        es: "TAG (table) de color de texto de cabecera.",
        pl: "TAG (table) – kolor tekstowy.",
        uk: "TAG (table) заголовок текстового кольору.",
        "zh-cn": "TAG (table)位头目。.",
    },
    header_font_size: {
        en: "TAG (table) header font size.",
        de: "TAG (table) Header Schriftgröße.",
        ru: "TAG (table) размер шрифта.",
        pt: "TAG (table) tamanho da fonte do cabeçalho.",
        nl: "Tag (table) koper lettertype.",
        fr: "TAG (table) header font size.",
        it: "TAG (table) intestazione formato carattere.",
        es: "TAG (table) header font size.",
        pl: "TAG (table) – typ czcionki.",
        uk: "TAG (table) розмір заголовка.",
        "zh-cn": "TAG (table)名导师规模。.",
    },
    header_font: {
        en: "TAG (table) header font.",
        de: "TAG (table) Header Schriftart.",
        ru: "TAG (table) шрифт заголовка.",
        pt: "Fonte de cabeçalho TAG (table).",
        nl: "Tag (table) hoofdrol.",
        fr: "Police TAG (table) en-tête.",
        it: "TAG (table) intestazione font.",
        es: "TAG (table) header font.",
        pl: "TAG (table).",
        uk: "TAG (table) заголовок шрифту.",
        "zh-cn": "TAG (table)头工程师。.",
    },
    header_linear_color_1: {
        en: "TAG (table) header linear color 1.",
        de: "TAG (table) Header lineare Farbe 1.",
        ru: "TAG (table) линейный цвет 1.",
        pt: "Cor linear de cabeçalho TAG (table) 1.",
        nl: "Tag (table) hoofd lineaire kleur 1.",
        fr: "Couleur linéaire TAG (table) en-tête 1.",
        it: "TAG (table) intestazione colore lineare 1.",
        es: "TAG (table) Header linear color 1.",
        pl: "TAG (table) koloru liniowego 1.",
        uk: "TAG (table) заголовок лінійного кольору 1.",
        "zh-cn": "TAG (table)头寸ar颜色1.",
    },
    header_linear_color_2: {
        en: "TAG (table) header linear color 2.",
        de: "TAG (table) Header lineare Farbe 2.",
        ru: "TAG (table) линейный цвет 2.",
        pt: "Cor linear de cabeçalho TAG (table) 2.",
        nl: "Tag (table) hoofd lineaire kleur 2.",
        fr: "Couleur linéaire TAG (table) en-tête 2.",
        it: "TAG (table) intestazione colore lineare 2.",
        es: "TAG (table) Header linear color 2.",
        pl: "TAG (table) koloru liniowego 2.",
        uk: "TAG (table) заголовок лінійного кольору 2.",
        "zh-cn": "TAG (table)头寸ar颜色2.",
    },
    ID: {
        en: "ID",
        de: "ID",
        ru: "КОД",
        pt: "ID",
        nl: "ID",
        fr: "ID",
        it: "ID",
        es: "ID",
        pl: "ID",
        uk: "ІМ'Я",
        "zh-cn": "ID ID",
    },
    Header_From: {
        en: "From",
        de: "Von",
        ru: "Из",
        pt: "A partir de",
        nl: "Van",
        fr: "De",
        it: "Da",
        es: "Desde",
        pl: "From",
        uk: "З",
        "zh-cn": "二. 从从从自来起",
    },
    Header_Subject: {
        en: "Subject",
        de: "Betreff",
        ru: "Тема",
        pt: "Assunto",
        nl: "Vertaling:",
        fr: "Subject",
        it: "Oggetto",
        es: "Asunto",
        pl: "Subject",
        uk: "Головна",
        "zh-cn": "议 题",
    },
    Header_Date: {
        en: "Date",
        de: "Datum",
        ru: "Дата",
        pt: "Data",
        nl: "Datum",
        fr: "Date",
        it: "Data",
        es: "Fecha",
        pl: "D",
        uk: "Дата",
        "zh-cn": "日期",
    },
    Header_Content: {
        en: "Content",
        de: "Inhalt",
        ru: "Содержание",
        pt: "Conteúdo",
        nl: "Content",
        fr: "Table des matières",
        it: "Contenuto",
        es: "Índice",
        pl: "Konfrontacja",
        uk: "Зміст",
        "zh-cn": "内容",
    },
    Header_SEQ: {
        en: "SEQ",
        de: "SEQ",
        ru: "СЕК",
        pt: "SEQ",
        nl: "SEQ",
        fr: "SEQ",
        it: "SEQ",
        es: "SEQ",
        pl: "SERCE",
        uk: "ПРОДАКШН",
        "zh-cn": "菲律宾",
    },
    headline_height: {
        en: "Headline height",
        de: "Kopfhöhe",
        ru: "Высота заголовка",
        pt: "Altura do título",
        nl: "Hoofdlijn lengte",
        fr: "Hauteur de la tête",
        it: "Altezza della testa",
        es: "Altura del título",
        pl: "Headline height",
        uk: "Висота лінії",
        "zh-cn": "标题高",
    },
    headline_color: {
        en: "Headline color",
        de: "Kopffarbe",
        ru: "Цвет заголовка",
        pt: "Cor do título",
        nl: "Hoofdlijn kleur",
        fr: "Couleur Headline",
        it: "Colore della testa",
        es: "Color de encabezado",
        pl: "Kolor",
        uk: "Колір лінії",
        "zh-cn": "标题",
    },
    headline_font_size: {
        en: "Headline font size",
        de: "Headline Schriftgröße",
        ru: "Размер шрифта Headline",
        pt: "Tamanho da fonte do título",
        nl: "Hoofdlijn lettertype",
        fr: "Headline font size",
        it: "Formato del carattere",
        es: "Tamaño de la fuente",
        pl: "Fontanny",
        uk: "Розмір основного шрифту",
        "zh-cn": "导 言",
    },
    headline_style: {
        en: "Headline style",
        de: "Headline Style",
        ru: "Headline стиль",
        pt: "Estilo de título",
        nl: "Hoofdlijn stijl",
        fr: "Style Headline",
        it: "Stile di testa",
        es: "Estilo de encabezado",
        pl: "Stylisko headline",
        uk: "Стиль лінії",
        "zh-cn": "标题风格",
    },
    headline_underlined: {
        en: "Heading underlined",
        de: "Unterstrichen",
        ru: "Заголовок подчеркнут",
        pt: "Rubrica sublinhada",
        nl: "Ondersteuning",
        fr: "Heading underlined",
        it: "Denominazione sottolineata",
        es: "Encabezamiento subrayado",
        pl: "Headlong underlined",
        uk: "Подається згідно з",
        "zh-cn": "标题强调",
    },
    headline_underlined_color: {
        en: "Heading underlined color",
        de: "Heading unterstrichene Farbe",
        ru: "Заголовок подчеркнутый цвет",
        pt: "Cor sublinhada de cabeça",
        nl: "Vertaling:",
        fr: "Tête de couleur soulignée",
        it: "Intestazione colore sottolineato",
        es: "Cabeza de color subrayado",
        pl: "Głowa podkreślona koloru",
        uk: "Подається згідно з кольором",
        "zh-cn": "标题突出强调颜色",
    },
    headline_column_width: {
        en: "Headline column width %s (e.g. auto or px)",
        de: "Kopfzeilenbreite %s (z.B. Auto oder px)",
        ru: "Ширина колонны %s (например, авто или px)",
        pt: "Largura da coluna %s (por exemplo, auto ou px)",
        nl: "Hoofdlijn column width %s (e.g auto of px)",
        fr: "Hauteur de la colonne %s (p. ex. auto ou px)",
        it: "Larghezza colonna intestata %s (ad esempio auto o px)",
        es: "Ancho de columna %s (por ejemplo, auto o px)",
        pl: "Kolumna główna nr %s (np. auto lub px)",
        uk: "Ширина колонки %s (наприклад, автоматичний або px)",
        "zh-cn": "标题第%s栏(如汽车或牙)",
    },
    headline_align_column: {
        en: "align column %s",
        de: "spalte %s ausrichten",
        ru: "выровнять колонну %s",
        pt: "coluna de alinhamento %s",
        nl: "align column %s",
        fr: "aligner la colonne %s",
        it: "colonna allineare %s",
        es: "columna %s",
        pl: "kolumna %s",
        uk: "стовпчик вирівнювання %s",
        "zh-cn": "第%s条",
    },
    top_text_color: {
        en: "TOP text color",
        de: "TOP Textfarbe",
        ru: "ТОП цвет текста",
        pt: "Cor de texto TOP",
        nl: "Top sms kleur",
        fr: "Couleur du texte TOP",
        it: "Colore del testo TOP",
        es: "Color de texto",
        pl: "Okładka",
        uk: "Колір тексту",
        "zh-cn": "案文",
    },
    top_text: {
        en: "TOP text",
        de: "TOP-Text",
        ru: "ТОП-текст",
        pt: "Texto do TOP",
        nl: "Top",
        fr: "Texte TOP",
        it: "Testo TOP",
        es: "Texto de la página",
        pl: "Tekst TOP",
        uk: "Головна",
        "zh-cn": "案文",
    },
    top_last_update: {
        en: "Last update:",
        de: "Letzte Aktualisierung:",
        ru: "Последнее обновление:",
        pt: "Última atualização:",
        nl: "Laatste update:",
        fr: "Dernière mise à jour :",
        it: "Ultimo aggiornamento:",
        es: "Última actualización:",
        pl: "Ostatnia aktualizacja",
        uk: "Останнє оновлення:",
        "zh-cn": "上次更新:",
    },
    top_font: {
        en: "TOP font",
        de: "TOP Schriftart",
        ru: "TOP шрифт",
        pt: "Fonte TOP",
        nl: "Top font",
        fr: "Police TOP",
        it: "TOP font",
        es: "Fuente TOP",
        pl: "TOP",
        uk: "Топ шрифт",
        "zh-cn": "三、结 论",
    },
    top_font_size: {
        en: "TOP font size",
        de: "TOP Schriftgröße",
        ru: "TOP размер шрифта",
        pt: "Tamanho da fonte TOP",
        nl: "ToP font maat",
        fr: "Taille de police TOP",
        it: "Dimensione del carattere TOP",
        es: "Tamaño de fuente TOP",
        pl: "TOP",
        uk: "Розмір шрифту",
        "zh-cn": "排 度",
    },
    top_font_weight: {
        en: "TOP font weight",
        de: "TOP Schriftstärke",
        ru: "TOP вес шрифта",
        pt: "Peso da fonte TOP",
        nl: "ToP font gewicht",
        fr: "Poids de police TOP",
        it: "TOP font peso",
        es: "TOP font weight",
        pl: "TOP",
        uk: "Максимальна вага шрифту",
        "zh-cn": "排 权",
    },
    mails_today_color: {
        en: "Font color eMails today (even)",
        de: "Schriftfarbe eMails heute (gerade)",
        ru: "Цвет шрифта eMails сегодня (даже)",
        pt: "Cor da fonte eMails hoje (even)",
        nl: "Font color eMails vandaag (even)",
        fr: "Font color eMails aujourd'hui (même)",
        it: "Colore del carattere eMails oggi (anche)",
        es: "EMails de color fuente hoy (incluso)",
        pl: "Gąsienny kolor eMails Today (ang.)",
        uk: "Шрифт кольорових електронних листів сьогодні (навіть)",
        "zh-cn": "今天福特·马利斯(11)",
    },
    mails_nextday_color_even: {
        en: "Font color emails other day (even)",
        de: "Schriftfarbe E-Mails anderen Tag (gerade)",
        ru: "Цвет шрифта emails other day (even)",
        pt: "E-mails de cor da fonte no outro dia (even)",
        nl: "Vontkleurige e-mails onlangs",
        fr: "Font color emails other day (even)",
        it: "Font color email altro giorno (anche)",
        es: "Correos electrónicos de color fuente otro día (incluso)",
        pl: "Font color emails Other Day (ang.)",
        uk: "Шрифт кольорових листів в інший день",
        "zh-cn": "弗朗索特·明特邮(11)",
    },
    mails_nextday_color_odd: {
        en: "Font color emails other day (odd)",
        de: "Schriftfarbe E-Mails anderen Tag (ungrade)",
        ru: "Цвет шрифта emails other day (odd)",
        pt: "E-mails de cor da fonte no outro dia (odd)",
        nl: "Vont kleur e-mails onlangs",
        fr: "Font color emails other day (odd)",
        it: "Font color emails altro giorno (odd)",
        es: "Correos electrónicos de color fuente otro día (odd)",
        pl: "Font color emails another day (odd.)",
        uk: "Фонтан кольорові електронні листи в інший день (odd)",
        "zh-cn": "弗朗索特·明特色电子邮件",
    },
    mails_today_color_odd: {
        en: "Font color eMails today (odd)",
        de: "Schriftfarbe eMails heute (ungrade)",
        ru: "Цвет шрифта eMails сегодня (odd)",
        pt: "Cor da fonte eMails hoje (odd)",
        nl: "Font color eMails vandaag (Godd)",
        fr: "Font color eMails aujourd'hui (odd)",
        it: "Colore del carattere eMails oggi (odd)",
        es: "Font color eMails today (odd)",
        pl: "Gąsienny kolor eMails (odd.)",
        uk: "Шрифт кольорових електронних листів сьогодні (odd)",
        "zh-cn": "今天福特·马利斯(odd)",
    },
    mails_even_color: {
        en: "Mails background color with even number.",
        de: "Mails Hintergrundfarbe mit gerader Nummer.",
        ru: "Почты фоновый цвет с даже номером.",
        pt: "Mails cor de fundo com número uniforme.",
        nl: "Mails achtergrond kleur met zelfs nummer.",
        fr: "Mails couleur de fond avec même numéro.",
        it: "Mails sfondo colore con numero pari.",
        es: "Color de fondo de correos con incluso número.",
        pl: "Mailski kolor tła z liczbą.",
        uk: "Колір фону пошти з парним числом.",
        "zh-cn": "马伊尔背景甚至数字。.",
    },
    mails_odd_color: {
        en: "Mails background color with odd number.",
        de: "Mails Hintergrundfarbe mit ungeraden Nummer.",
        ru: "Почты фоновый цвет с нечетным номером.",
        pt: "Mails cor de fundo com número estranho.",
        nl: "Mails achtergrondkleur met vreemd nummer.",
        fr: "Mails couleur de fond avec un nombre étrange.",
        it: "Posta colore di sfondo con numero dispari.",
        es: "Color de fondo de correos con número extraño.",
        pl: "Mailski kolor tła o dziwnej liczbie.",
        uk: "Колір фону пошти з непарним числом.",
        "zh-cn": "马伊尔背景与数字相差。.",
    },
    short_subject: {
        en: "Shorten subject.",
        de: "Verkürzung des Themas.",
        ru: "Сокращенная тема.",
        pt: "Encurtar o assunto.",
        nl: "Een kort onderwerp.",
        fr: "Abrégé.",
        it: "Ridurre argomento.",
        es: "Acortar el tema.",
        pl: "Krótki temat.",
        uk: "Скорочення суб'єкта.",
        "zh-cn": "短期问题。.",
    },
    short_content: {
        en: "Shorten content.",
        de: "Verkürzung des Inhalts.",
        ru: "Сократите контент.",
        pt: "Encurtar conteúdo.",
        nl: "Gevangene inhoud.",
        fr: "Plus de contenu.",
        it: "Ridurre il contenuto.",
        es: "Acortar contenido.",
        pl: "Zawartość.",
        uk: "Скорочення вмісту.",
        "zh-cn": "内容较短。.",
    },
    "no inbox": {
        en: "No inbox specified",
        de: "Keine Posteingang angegeben",
        ru: "Не указан почтовый ящик",
        pt: "Nenhuma caixa de entrada especificada",
        nl: "Geen inbox gespecificeerd",
        fr: "Aucune boîte spécifiée",
        it: "Nessuna casella di posta specificata",
        es: "No se especifica la caja",
        pl: "Niepodpisywane",
        uk: "Немає в папці вказаний",
        "zh-cn": "未具体说明的箱",
    },
    "Apply html changes": {
        en: "Apply html changes",
        de: "HTML-Änderungen anwenden",
        ru: "Применить html изменения",
        pt: "Aplicar alterações html",
        nl: "Verandering",
        fr: "Apply html changes",
        it: "Applicare modifiche html",
        es: "Apply html changes",
        pl: "Zmienia się html",
        uk: "Застосувати зміни HTML",
        "zh-cn": "附录",
    },
    "Start Update": {
        en: "Start Update for device %s - %s - %s.",
        de: "Start Update für das Gerät %s - %s - %s.",
        ru: "Start Update для устройства %s - %s - %s.",
        pt: "Iniciar atualização para dispositivo %s - %s - %s.",
        nl: "Start Update voor apparaat %s - %s - %s.",
        fr: "Mettre à jour le dispositif %s - %s - %s.",
        it: "Avviare l'aggiornamento per il dispositivo %s - %s - %s.",
        es: "Iniciar actualización para el dispositivo %s - %s - %s.",
        pl: "Uruchomienie urządzenia %s - %s - %s.",
        uk: "Почати оновлення для пристрою %s - %s - %s.",
        "zh-cn": "B. 装置的最新情况 %s - %s - %s.",
    },
    "No Update": {
        en: "An email with the SeqNo %s of %s was updated outside of max - %s.",
        de: "Eine E-Mail mit der SeqNo %s von %s wurde außerhalb von max aktualisiert - %s.",
        ru: "Электронная почта с SeqNo %s из %s была обновлена за пределами макс - %s.",
        pt: "Um e-mail com o SeqNo %s de %s foi atualizado fora do max - %s.",
        nl: "Een e-mail met de SeqNo %s van %s werd geüpload buiten Max - %s.",
        fr: "Un email avec l'SeqNo %s de %s a été mis à jour en dehors de max - %s.",
        it: "Un'email con l'SeqNo %s di %s è stata aggiornata al di fuori del max - %s.",
        es: "Un correo electrónico con el SeqNo %s de %s fue actualizado fuera de máx - %s.",
        pl: "E-mail z SeqNo %s z %s został zaktualizowany poza maxą - %s.",
        uk: "Останнє повідомлення від SeqNo %s від %s було оновлено за межами макс - %s.",
        "zh-cn": "在三氯米以外更新了与国际发展部%s %s个电子邮件。. - %s.",
    },
    "Start new Mail": {
        en: "There is %s new mail for device %s",
        de: "Es gibt %s neue Post für das Gerät %s",
        ru: "Есть %s новая почта для устройства %s",
        pt: "Há %s novo correio para dispositivo %s",
        nl: "Er is %s nieuwe post voor apparaat %s",
        fr: "Il y a %s nouveau courrier pour l'appareil %s",
        it: "C'è %s nuova posta per il dispositivo %s",
        es: "Hay %s nuevo correo para el dispositivo %s",
        pl: "Istnieje %s nowa poczta dla urządzenia %s",
        uk: "Є %s нова пошта для пристрою %s",
        "zh-cn": "有%s个新的装置邮件 %s",
    },
    "Start new Mails": {
        en: "There is %s new mails for device %s",
        de: "Es gibt %s neue Posts für das Gerät %s",
        ru: "Есть %s новых почты для устройства %s",
        pt: "Há %s novos e-mails para dispositivo %s",
        nl: "Er zijn %s nieuwe posten voor apparaat %s",
        fr: "Il y a %s nouveaux mails pour le dispositif %s",
        it: "Ci sono %s nuove mail per il dispositivo %s",
        es: "Hay %s nuevos correos para el dispositivo %s",
        pl: "Istnieje %s nowe poczty dla urządzenia %s",
        uk: "Є %s нові листи для пристрою %s",
        "zh-cn": "有%s个新的装置邮件 %s",
    },
    Restart: {
        en: "Restart IMAP connection from device %s in %s seconds.",
        de: "Start IMAP-Verbindung vom Gerät %s in %s Sekunden.",
        ru: "Перезапустите подключение IMAP с устройства %s за %s секунд.",
        pt: "Reinicie a conexão IMAP do dispositivo %s em %s segundos.",
        nl: "Start IMAP-verbinding met apparaat %s in %s seconden.",
        fr: "Restart Connexion IMAP de l'appareil %s en %s secondes.",
        it: "Riavviare la connessione IMAP dal dispositivo %s in %s secondi.",
        es: "Reinicie la conexión IMAP desde el dispositivo %s en %s segundos.",
        pl: "Restart IMAP z urządzenia %s w %s sekund.",
        uk: "З'єднання ІМП від пристрою %s в %s секунд.",
        "zh-cn": "在%s秒中,从装置%s处重新启动单元。.",
    },
    "Restart now": {
        en: "The IMAP Connection %s will now restart.",
        de: "Die IMAP-Verbindung %s wird nun neu gestartet.",
        ru: "IMAP Connection %s теперь перезагрузится.",
        pt: "A Ligação IMAP %s agora reiniciará.",
        nl: "De IMAP Connectie %s zal nu herstarten.",
        fr: "La connexion IMAP %s va maintenant redémarrer.",
        it: "La connessione IMAP %s si riavvia.",
        es: "La conexión IMAP %s se reiniciará.",
        pl: "IMAP Connection %s będzie teraz restartować.",
        uk: "Підключення IMAP %s тепер перезапустіть.",
        "zh-cn": "IMAP Connection %s现在将重新启动。.",
    },
    "last activity": {
        en: "last activity",
        de: "Letzte Aktivität",
        ru: "последняя деятельность",
        pt: "última atividade",
        nl: "laatste activiteit",
        fr: "dernière activité",
        it: "ultima attività",
        es: "última actividad",
        pl: "ostatnia aktywność",
        uk: "остання активність",
        "zh-cn": "最后一次活动",
    },
    "json last activity": {
        en: "json last activity",
        de: "JSON letzte Aktivität",
        ru: "json последняя активность",
        pt: "json última atividade",
        nl: "json laatste activiteit",
        fr: "json dernière activité",
        it: "json ultima attività",
        es: "json última actividad",
        pl: "ostatnia aktywność jsonów",
        uk: "json остання активність",
        "zh-cn": "json 最后一次活动",
    },
    "timestamp last activity": {
        en: "timestamp last activity",
        de: "zeitstempel letzte aktivität",
        ru: "timetamp последняя активность",
        pt: "última atividade",
        nl: "laatste activiteit",
        fr: "dernière activité",
        it: "timestamp ultima attività",
        es: "tiempo de última actividad",
        pl: "czasoprzestrzeń",
        uk: "своєчасна робота",
        "zh-cn": "最后一次活动的时间",
    },
    update: {
        en: "Update",
        de: "Aktualisierung",
        ru: "Обновление",
        pt: "Atualização",
        nl: "Update",
        fr: "Mise à jour",
        it: "Aggiornamento",
        es: "Actualización",
        pl: "Update",
        uk: "Новини",
        "zh-cn": "最新资料",
    },
    "new mail": {
        en: "New mail",
        de: "Neue Post",
        ru: "Новая почта",
        pt: "Novo correio",
        nl: "Nieuwe post",
        fr: "Nouveau courrier",
        it: "Nuova posta",
        es: "Nuevo correo",
        pl: "Poczta",
        uk: "Нова пошта",
        "zh-cn": "新员额",
    },
    Message: {
        en: "Message: %s",
        de: "Nachricht: %s",
        ru: "Сообщение: %s",
        pt: "Mensagem: %s",
        nl: "Bericht: %s",
        fr: "Message: %s",
        it: "Messaggio: %s",
        es: "Mensaje: %s",
        pl: "Message: %s",
        uk: "Новини: %s",
        "zh-cn": "导 言: %s",
    },
    footer: {
        en: "%s mails read from %s",
        de: "%s Posts von %s eingelesen",
        ru: "%s писем чтения из %s",
        pt: "%s mails lido a partir de %s",
        nl: "%s mails van %s",
        fr: "%s messages lus à partir de %s",
        it: "%s mail leggere da %s",
        es: "%s correos leídos de %s",
        pl: "%s pocztowych odczytów z %s kart",
        uk: "%s пошти з %s",
        "zh-cn": "%s个邮件从%s个改为",
    },
    "not found imap": {
        en: "Can't find the IMAP %s.",
        de: "Das IMAP %s kann nicht gefunden werden.",
        ru: "Не можете найти IMAP %s.",
        pt: "Não encontro o IMAP %s.",
        nl: "Ik kan de IMAP %s niet vinden.",
        fr: "Impossible de trouver le IMAP %s.",
        it: "Non trovo l'IMAP %s.",
        es: "No puedo encontrar el IMAP %s.",
        pl: "Nie można znaleźć IMAP %s.",
        uk: "Не знайти ІМП %s.",
        "zh-cn": "坎特发现,IMAP%s.",
    },
    "IMAP disabled": {
        en: "IMAP %s is disabled",
        de: "IMAP %s ist deaktiviert",
        ru: "IMAP %s отключен",
        pt: "IMAP %s está desativado",
        nl: "IMAP %s is gehandicapt",
        fr: "IMAP %s est désactivé",
        it: "IMAP %s è disabilitato",
        es: "IMAP %s está desactivada",
        pl: "IMAP %s jest niepełnosprawna",
        uk: "IMAP %s вимкнено",
        "zh-cn": "IMAP %s是残疾人",
    },
    Alert: {
        en: "Alert: %s - %s",
        de: "Alarm: %s - %s",
        ru: "Оповещение: %s - %s",
        pt: "Alerta: %s - %s",
        nl: "Alarm: %s - %s",
        fr: "Alerte : %s - %s",
        it: "Avviso: %s - %s",
        es: "Alerta: %s - %s",
        pl: "Alert: %s - %s",
        uk: "Вставити: %s - %s",
        "zh-cn": "核证: %s - %s",
    },
    "No IMAP selected": {
        en: "No IMAP selected",
        de: "Keine IMAP ausgewählt",
        ru: "Не выбрано IMAP",
        pt: "Nenhum IMAP selecionado",
        nl: "Geen IMAP geselecteerd",
        fr: "Aucun IMAP sélectionné",
        it: "Nessun IMAP selezionato",
        es: "No se ha seleccionado IMAP",
        pl: "Nikt nie wybrany",
        uk: "Не вибрано IMAP",
        "zh-cn": "没有选择的IMAP",
    },
    "UID validity changes": {
        en: "UID validity changes %s - %s",
        de: "Änderungen der Gültigkeit %s - %s",
        ru: "Изменения действия UID %s - %s",
        pt: "Alterações de validade UID %s - %s",
        nl: "UID geldigheid verandert %s - %s",
        fr: "Modification de la validité de l ' UID %s - %s",
        it: "Modifiche della validità dell'IDU %s - %s",
        es: "Cambios de validez UID %s - %s",
        pl: "Zmienność ustrojowa %s - %s",
        uk: "Зміни в дії UID %s - %s",
        "zh-cn": "B. 开发有效性的变化 %s - %s",
    },
    "EMail deleted": {
        en: "Email deleted outside of scope - No Update %s - %s",
        de: "E-Mail außerhalb des Geltungsbereichs gelöscht - Kein Update %s - %s",
        ru: "Email удален за пределами области - Нет обновления %s - %s",
        pt: "Email excluído fora do escopo - Nenhuma atualização %s - %s",
        nl: "E-mail verwijderd van scope, geen Update %s - %s",
        fr: "Courriel supprimé en dehors de la portée - Pas de mise à jour %s - %s",
        it: "Email cancellata al di fuori del campo - No Update %s - %s",
        es: "Correo electrónico borrado fuera de alcance - No actualización %s - %s",
        pl: "Email usunął poza zasięgiem - No Update %s - %s",
        uk: "Видаліть електронну пошту за межі - No Update %s - %s",
        "zh-cn": "电子邮件在范围之外删除——最新资料 %s - %s",
    },
    move_copy: {
        en: "deleted or moved",
        de: "gelöscht oder verschoben",
        ru: "удален или перемещен",
        pt: "excluído ou movido",
        nl: "gewist of verplaatst",
        fr: "supprimé ou déplacé",
        it: "cancellato o spostato",
        es: "eliminado o movido",
        pl: "usuwać lub usunąć",
        uk: "видалення або переміщення",
        "zh-cn": "删除或移出",
    },
    "EMail deleted in scope": {
        en: "E-mails within the scope deleted - Update starts %s - %s",
        de: "E-Mails im gelöschten Bereich - Update beginnt %s - %s",
        ru: "E-mail в рамках удаленного объема - Обновление начинается %s - %s",
        pt: "E-mails dentro do escopo excluído - Atualização começa %s - %s",
        nl: "E-mails binnen de scope gewist - Update begint %s - %s",
        fr: "E-mails dans le champ supprimé - Mise à jour commence %s - %s",
        it: "E-mail all'interno del campo cancellato - Inizio aggiornamento %s - %s",
        es: "E-mails dentro del alcance eliminado - Actualización comienza %s - %s",
        pl: "E-maile wewnątrz skasowania - Update zaczyna się od e-maili %s - %s",
        uk: "E-mails в межах обраного списку - Оновлення починається %s - %s",
        "zh-cn": "删除范围内的电子邮件——最新情况开始 %s - %s",
    },
    "BLOCKLY value": {
        en: "BLOCKLY value for IMAP:",
        de: "BLOCKLY-Wert für IMAP:",
        ru: "BLOCKLY значение для IMAP:",
        pt: "Valor BLOCKLY para IMAP:",
        nl: "BLOCKly waarde voor IMAP:",
        fr: "Valeur BLOCKLY pour IMAP:",
        it: "Valore BLOCKLY per IMAP:",
        es: "Valor BLOCKLY para IMAP:",
        pl: "BLOCKLY value for IMAP: IMAP (ang.)",
        uk: "БЛОКЛІ значення для ІМП:",
        "zh-cn": "BLOCKLY IMAP的价值:",
    },
    "Error parse": {
        en: "Error JSON parse",
        de: "Fehler JSON parse",
        ru: "Ошибка JSON parse",
        pt: "Erro JSON parse",
        nl: "Error JSON paren",
        fr: "Erreur JSON parse",
        it: "Errore JSON parse",
        es: "Error JSON parse",
        pl: "Error JSON parse",
        uk: "Помилка JSON",
        "zh-cn": "Error",
    },
    "Error search": {
        en: "Error searching emails",
        de: "Fehler beim Suchen von E-Mails",
        ru: "Ошибка поиска писем",
        pt: "Busca de erros",
        nl: "Error zoekt e-mails",
        fr: "Erreur recherche emails",
        it: "E-mail di ricerca errori",
        es: "Correos electrónicos de búsqueda de errores",
        pl: "Error Searching email (ang.)",
        uk: "Помилка пошуку електронних листів",
        "zh-cn": "查询电子邮件",
    },
    "Mailbox is empty": {
        en: "Mailbox is empty",
        de: "Mailbox ist leer",
        ru: "Почтовый ящик пуст",
        pt: "Caixa de correio está vazia",
        nl: "Mailbox is leeg",
        fr: "Mailbox est vide",
        it: "Mailbox è vuoto",
        es: "Mailbox está vacío",
        pl: "Mailbox jest pusty",
        uk: "Порожня поштова скринька",
        "zh-cn": "邮件箱空",
    },
    "Cannot found Mails": {
        en: "Can't find any emails",
        de: "Kann keine E-Mails finden",
        ru: "Не можете найти электронные письма",
        pt: "Não consigo encontrar e-mails",
        nl: "Kan geen e-mail vinden",
        fr: "Je ne trouve pas de mails",
        it: "Non riesco a trovare email",
        es: "No puedo encontrar ningún email",
        pl: "Nie można znaleźć żadnych e-maili",
        uk: "Не знайдено ніяких електронних листів",
        "zh-cn": "坎特发现任何电子邮件",
    },
    "IMAP connection": {
        en: "IMAP %s connection status: %s",
        de: "IMAP %s Verbindungsstatus: %s",
        ru: "Статус подключения IMAP %s: %s",
        pt: "Status de conexão IMAP %s: %s",
        nl: "IMAP %s connectie status: %s",
        fr: "Statut de connexion IMAP %s: %s",
        it: "Stato di connessione IMAP %s: %s",
        es: "IMAP %s estado de conexión: %s",
        pl: "strona oficjalna IMAP %s: %s",
        uk: "статус підключення ІМП %s: %s",
        "zh-cn": "IMAP %s的联系地位: %s",
    },
    "No connection": {
        en: "No connection: %s",
        de: "Keine Verbindung: %s",
        ru: "Нет подключения: %s",
        pt: "Sem conexão: %s",
        nl: "Geen verband: %s",
        fr: "Pas de connexion: %s",
        it: "Nessuna connessione: %s",
        es: "Sin conexión: %s",
        pl: "Brak połączenia: %s",
        uk: "Немає підключення: %s",
        "zh-cn": "没有联系: %s",
    },
    "Cannot find translation": {
        en: "Cannot find translation for %s.",
        de: "Finde keine Übersetzung für %s.",
        ru: "Не можете найти перевод для %s.",
        pt: "Não encontro tradução para %s.",
        nl: "Kan geen vertaling vinden voor %s.",
        fr: "Impossible de trouver la traduction pour %s.",
        it: "Non riesco a trovare la traduzione per %s.",
        es: "No se puede encontrar traducción para %s.",
        pl: "Cannot znalazł tłumaczenie na %s.",
        uk: "Не можна знайти переклад для %s.",
        "zh-cn": "传真:%s.",
    },
    "Token was created": {
        en: "Token was created for %s.",
        de: "Token wurde für %s erstellt.",
        ru: "Токен был создан для %s.",
        pt: "Token foi criado para %s.",
        nl: "Token is voor %s gemaakt.",
        fr: "Token a été créé pour %s.",
        it: "Token è stato creato per %s.",
        es: "Token fue creado para %s.",
        pl: "Token powstał na %s.",
        uk: "Token був створений для %s.",
        "zh-cn": "创建了%s 000美元.",
    },
    "Token cannot be created": {
        en: "Token cannot be created. Please try login with password. - %s",
        de: "Token kann nicht erzeugt werden. Bitte versuchen Sie Login mit Passwort. - %s",
        ru: "Токен не может быть создан. Пожалуйста, попробуйте войти с паролем. - %s",
        pt: "Token não pode ser criado. Por favor, tente login com senha. - %s",
        nl: "Token kan niet gemaakt worden. Probeer alsjeblieft login met wachtwoord. - %s",
        fr: "Le jeton ne peut pas être créé. Veuillez essayer de vous connecter avec mot de passe. - %s",
        it: "Token non può essere creato. Si prega di provare il login con la password. - %s",
        es: "Token no se puede crear. Por favor, intente iniciar sesión con contraseña. - %s",
        pl: "Nie może być stworzony. Proszę o login z hasłem. - %s",
        uk: "Не можна створювати токени. Будь ласка, спробуйте логін з паролем. - %s",
        "zh-cn": "不能在此基础上建立。 请尝试用密码。. - %s",
    },
    "Token could not be created": {
        en: "Token could not be created. - %s",
        de: "Token konnte nicht erstellt werden. - %s",
        ru: "Токен не может быть создан. - %s",
        pt: "Token não poderia ser criado. - %s",
        nl: "Token kon niet gemaakt worden. - %s",
        fr: "Token ne pouvait pas être créé. - %s",
        it: "Token non poteva essere creato. - %s",
        es: "Token no podía ser creado. - %s",
        pl: "Nie mógł być stworzony. - %s",
        uk: "Токен не може бути створений. - %s",
        "zh-cn": "不能在此基础上建立。. - %s",
    },
    "Security-ID": {
        en: "Can't find the Security-ID. - %s",
        de: "Ich kann die Sicherheits-ID nicht finden. - %s",
        ru: "Не можете найти ID безопасности. - %s",
        pt: "Não encontro o ID de Segurança. - %s",
        nl: "Ik kan de beveiliging niet vinden. - %s",
        fr: "Je ne trouve pas l'ID de sécurité. - %s",
        it: "Non trovo l'ID della sicurezza. - %s",
        es: "No puedo encontrar al Departamento de Seguridad. - %s",
        pl: "Nie można znaleźć kryteriów bezpieczeństwa. - %s",
        uk: "Не можна знайти Security-ID. - %s",
        "zh-cn": "堪称“安全与发展”。. - %s",
    },
    "none select": {
        en: "none select",
        de: "keine Auswahl",
        ru: "не выбрать",
        pt: "nenhum select",
        nl: "geen enkele",
        fr: "aucune sélection",
        it: "nessuno seleziona",
        es: "ninguno",
        pl: "none selekcji",
        uk: "не вибрати",
        "zh-cn": "无选择",
    },
    "Type recent": {
        en: "Type recent %s - %s - %s",
        de: "Typ neu %s - %s - %s",
        ru: "Тип Недавний %s - %s - %s",
        pt: "Tipo recente %s - %s - %s",
        nl: "Type vertaling %s - %s - %s",
        fr: "Type récent %s - %s - %s",
        it: "Tipo recente %s - %s - %s",
        es: "Tipo reciente %s - %s - %s",
        pl: "Typ ostatni %s - %s - %s",
        uk: "Останній %s - %s - %s",
        "zh-cn": "近期的类型 %s - %s - %s",
    },
    Type: {
        en: "Type %s - %s - %s",
        de: "Art %s - %s - %s",
        ru: "Тип %s - %s - %s",
        pt: "Tipo %s - %s - %s",
        nl: "Type %s - %s - %s",
        fr: "Type %s - %s - %s",
        it: "Tipo %s - %s - %s",
        es: "Tipo %s - %s - %s",
        pl: "Typ %s - %s - %s",
        uk: "Тип %s - %s - %s",
        "zh-cn": "类型 %s - %s - %s",
    },
    json_code: {
        en: "e-Mail JSON",
        de: "e-Mail JSON",
        ru: "электронная почта JSON",
        pt: "e-Mail JSON",
        nl: "e-Mail JSON",
        fr: "e-Mail JSON",
        it: "e-mail JSON",
        es: "e-Mail JSON",
        pl: "e-Mail JSON",
        uk: "електронна пошта JSON",
        "zh-cn": "e-Mail JSON",
    },
    "Disable containers": {
        en: "Disable div.containers for jarvis",
        de: "Div.container für Jarvis deaktivieren",
        ru: "Отключить div.containers для jarvis",
        pt: "Desativar div.containers para jarvis",
        nl: "Disable div-containers",
        fr: "Disable div.containers for jarvis",
        it: "Disabilita div.containers per jarvis",
        es: "Desactivar div.containers para jarvis",
        pl: "Niezdolne div.containery dla jarvisów",
        uk: "Вимкнені див.контейнери для бані",
        "zh-cn": "A. 可以区分的 div. jarvis的拘留者",
    },
    "Choose content": {
        en: "Choose content",
        de: "Inhalt wählen",
        ru: "Выберите контент",
        pt: "Escolha o conteúdo",
        nl: "Kies inhoud",
        fr: "Choisir le contenu",
        it: "Scegli il contenuto",
        es: "Elija contenido",
        pl: "Choose content",
        uk: "Виберіть вміст",
        "zh-cn": "选择内容",
    },
    "IMAP namespaces": {
        en: "IMAP namespaces %s - %s",
        de: "IMAP Namespaces %s - %s",
        ru: "IMAP пространства %s - %s",
        pt: "Namespaces IMAP %s - %s",
        nl: "IMAP naamspace %s - %s",
        fr: "IMAP namespaces %s - %s",
        it: "Namespace IMAP %s - %s",
        es: "Espacios de nombre IMAP %s - %s",
        pl: "Strona oficjalna IMAP %s - %s",
        uk: "ІМП ім'я просторів %s - %s",
        "zh-cn": "IMAP 空间名称 %s - %s",
    },
    "IMAP delimiter": {
        en: "IMAP delimiter %s - %s",
        de: "IMAP-Begrenzer %s - %s",
        ru: "IMAP-дилер %s - %s",
        pt: "Delimitador IMAP %s - %s",
        nl: "IMAP delimiter %s - %s",
        fr: "IMAP delimiter %s - %s",
        it: "IMAP delimiter %s - %s",
        es: "IMAP delimitador %s - %s",
        pl: "IMAP delimiter %s - %s",
        uk: "ІМП дельимітер %s - %s",
        "zh-cn": "IMAP 限制 %s - %s",
    },
    "Set Flags": {
        en: "Set Flags: %s - %s - %s",
        de: "Flaggen festlegen: %s - %s - %s",
        ru: "Установите флаги: %s - %s - %s",
        pt: "Conjunto de bandeiras: %s - %s - %s",
        nl: "Set Flags: %s - %s - %s",
        fr: "Set Drapeaux: %s - %s - %s",
        it: "Set Bandiere: %s - %s - %s",
        es: "Set Flags: %s - %s - %s",
        pl: "Flaga: %s - %s - %s",
        uk: "Комплект Прапорів: %s - %s - %s",
        "zh-cn": "A. 排减量: %s - %s - %s",
    },
    TLSOPTION: {
        en: "Cannot TLSOPTION JSON.parse: %s - %s",
        de: "Kann nicht TLSOPTION JSON.parse: %s - %s",
        ru: "Не можете TLSOPTION JSON.parse: %s - %s",
        pt: "Não pode TLSOPTION JSON.parse: %s - %s",
        nl: "Kan TLSOPTION JSON niet uit elkaar halen: %s - %s",
        fr: "Cannot TLSOPTION JSON.parse: %s - %s",
        it: "Non può TLSOPTION JSON.parse: %s - %s",
        es: "No puede TLSOPTION JSON.parse: %s - %s",
        pl: "Strona internetowa JSON.parse: %s - %s",
        uk: "Не можна TLSOPTION JSON.parse: %s - %s",
        "zh-cn": "批准.",
    },
    Subscribe: {
        en: "Subscribe: %s - %s",
        de: "Abonnieren: %s - %s",
        ru: "Подписаться: %s - %s",
        pt: "Assinar: %s - %s",
        nl: "Vertaling: %s - %s",
        fr: "Abonnez-vous: %s - %s",
        it: "Iscriviti: %s - %s",
        es: "Suscríbete: %s - %s",
        pl: "Subscribe: %s - %s",
        uk: "Підписатися: %s - %s",
        "zh-cn": "分 法: %s - %s",
    },
    SetFlag: {
        en: "%s - %s",
        de: "%s - %s",
        ru: "%s - %s",
        pt: "%s - %s",
        nl: "%s - %s",
        fr: "%s - %s",
        it: "%s - %s",
        es: "%s - %s",
        pl: "%s - %s",
        uk: "%s - %s",
        "zh-cn": "%s - %s",
    },
    addBox: {
        en: "%s - %s",
        de: "%s - %s",
        ru: "%s - %s",
        pt: "%s - %s",
        nl: "%s - %s",
        fr: "%s - %s",
        it: "%s - %s",
        es: "%s - %s",
        pl: "%s - %s",
        uk: "%s - %s",
        "zh-cn": "%s - %s",
    },
    "IMAP Server": {
        en: "IMAP Server",
        de: "IMAP Server",
        ru: "IMAP сервер",
        pt: "Servidor IMAP",
        nl: "IMAP",
        fr: "IMAP Server",
        it: "Server IMAP",
        es: "IMAP Server",
        pl: "IMAP Server",
        uk: "Статус на сервери",
        "zh-cn": "IMAP Server",
    },
    "Last IMAP update": {
        en: "Last IMAP update",
        de: "Letztes IMAP Update",
        ru: "Последнее обновление IMAP",
        pt: "Última atualização IMAP",
        nl: "Laatste IMAP update",
        fr: "Dernière mise à jour IMAP",
        it: "Ultimo aggiornamento IMAP",
        es: "Última actualización de IMAP",
        pl: "Ostatnia aktualizacja IMAP",
        uk: "Останнє оновлення IMAP",
        "zh-cn": "最后一期行动计划更新",
    },
    Hostname: {
        en: "Hostname",
        de: "Hostname",
        ru: "Имя",
        pt: "Nome do anfitrião",
        nl: "Heetnaam",
        fr: "Hostname",
        it: "Nome host",
        es: "Nombre de host",
        pl: "Hostname",
        uk: "Логін",
        "zh-cn": "人质",
    },
    "Type is empty": {
        en: "Type is empty",
        de: "Typ ist leer",
        ru: "Тип пуст",
        pt: "O tipo está vazio",
        nl: "Type is leeg",
        fr: "Le type est vide",
        it: "Il tipo è vuoto",
        es: "El tipo está vacío",
        pl: "Typ jest pusty",
        uk: "Тип порожній",
        "zh-cn": "类型是空洞的。",
    },
    "Flag Type is empty": {
        en: "Flag Type is empty",
        de: "Flag Type ist leer",
        ru: "Тип флага пуст",
        pt: "Tipo de bandeira está vazio",
        nl: "Flag Type is leeg",
        fr: "Type de drapeau est vide",
        it: "Il tipo di bandiera è vuoto",
        es: "El tipo de bandera está vacío",
        pl: "Typ flagowy jest pusty",
        uk: "Прапор Тип порожній",
        "zh-cn": "落后类型是空洞的。",
    },
    Flags: {
        en: "Flags",
        de: "Flaggen",
        ru: "Флаги",
        pt: "Bandeiras",
        nl: "Flags",
        fr: "Drapeaux",
        it: "Bandiere",
        es: "Banderas",
        pl: "Flaga",
        uk: "Прапори",
        "zh-cn": "Flags",
    },
    "Flag Type": {
        en: "Flag Type",
        de: "Flaggentyp",
        ru: "Тип флага",
        pt: "Tipo de bandeira",
        nl: "Flag Type",
        fr: "Type de drapeau",
        it: "Tipo di bandiera",
        es: "Tipo de bandera",
        pl: "Typ flagowy",
        uk: "Тип Прапора",
        "zh-cn": "滞后类型。",
    },
    "Set Flag": {
        en: "Set Flag",
        de: "Flagge setzen",
        ru: "Установите флаг",
        pt: "Defina a bandeira",
        nl: "Zet Flag",
        fr: "Set Flag",
        it: "Set Flag",
        es: "Set Flag",
        pl: "Flaga",
        uk: "Комплект Прапор",
        "zh-cn": "排 值。",
    },
    "VIS command": {
        en: "VIS command",
        de: "VIS Befehl",
        ru: "Команда VIS",
        pt: "Comando VIS",
        nl: "VIS",
        fr: "VIS command",
        it: "Comando VIS",
        es: "VIS command",
        pl: "Dowództwo VIS",
        uk: "Команда VIS",
        "zh-cn": "指挥",
    },
    "Change folder": {
        en: "Change folder",
        de: "Ordner wechseln",
        ru: "Изменить папку",
        pt: "Alterar pasta",
        nl: "Verander de map",
        fr: "Changer de dossier",
        it: "Cambia cartella",
        es: "Cambiar carpeta",
        pl: "Zmiana folderów",
        uk: "Зміна папки",
        "zh-cn": "变化",
    },
    "Active folder": {
        en: "Active folder",
        de: "Aktiver Ordner",
        ru: "Активная папка",
        pt: "Pasta ativa",
        nl: "Actieve map",
        fr: "Dossier actif",
        it: "Cartella attiva",
        es: "Carpeta activa",
        pl: "Folder",
        uk: "Активна папка",
        "zh-cn": "A. 积极方面",
    },
    unread: {
        en: "unread",
        de: "ungelesen",
        ru: "непрочитан",
        pt: "não lido",
        nl: "niet gelezen",
        fr: "dégagez",
        it: "non letto",
        es: "sin leer",
        pl: "nieczyste",
        uk: "переглянути",
        "zh-cn": "无。",
    },
    "Infos current folder": {
        en: "Infos current folder",
        de: "Infos zum aktuellen Ordner",
        ru: "Информация актуальная папка",
        pt: "Info pasta atual",
        nl: "Info huidige map",
        fr: "Infos dossier courant",
        it: "Infos cartella corrente",
        es: "Infos carpeta actual",
        pl: "Aktualny",
        uk: "Поточна папка новин",
        "zh-cn": "当前信息",
    },
    INBOXFOLDER: {
        en: "Create datapoint (change_folder) for %s.",
        de: "Datapoint (change_folder) für %s erstellen.",
        ru: "Создать данные (change_folder) для %s.",
        pt: "Criar datapoint (change_folder) para %s.",
        nl: "Creëer datapoint (change_folder) voor %s.",
        fr: "Créer un point de données (change_folder) pour %s.",
        it: "Creare datapoint (change_folder) per %s.",
        es: "Crear punto de datos (change_folder) para %s.",
        pl: "Źródło danych (change_folder) dla %s.",
        uk: "Створення точки даних (change_folder) для %s.",
        "zh-cn": "A. 为%s人设立数据点(change_folder)。.",
    },
    "Status eMail folder": {
        en: "Status eMail folder",
        de: "Status eMail Ordner",
        ru: "Статус eMail папка",
        pt: "Status eMail pasta",
        nl: "Status eMail map",
        fr: "Dossier eMail",
        it: "Stato cartella eMail",
        es: "Carpeta de estado eMail",
        pl: "Status eMail folder",
        uk: "Статус папки електронної пошти",
        "zh-cn": "现状 eMail 倍",
    },
    "Connection attempt": {
        en: "Connection attempt limit reached. Please check your connection.",
        de: "Verbindungsversuchsgrenze erreicht. Bitte überprüfen Sie Ihre Verbindung.",
        ru: "Ограничение попытки соединения достигнуто. Пожалуйста, проверьте ваше соединение.",
        pt: "Limite de tentativa de conexão atingido. Por favor, verifique a sua ligação.",
        nl: "Connectiepolitie bereikt. Controleer alsjeblieft je verbinding.",
        fr: "Limite de tentative de connexion atteinte. Veuillez vérifier votre connexion.",
        it: "Limite di tentativo di connessione raggiunto. Controlla la connessione.",
        es: "Límite de intento de conexión alcanzado. Por favor, compruebe su conexión.",
        pl: "Rozpoczęła się próba połączenia. Pozwólcie sprawdzić swój związek.",
        uk: "Обмеження спроби підключення досягнуто. Будь ласка, перевірте підключення.",
        "zh-cn": "强制企图限制到来。 请检查你的联系。.",
    },
    Attachments: {
        en: "Attachments",
        de: "Anhänge",
        ru: "Приспособления",
        pt: "Anexos",
        nl: "Aanklachten",
        fr: "Attachements",
        it: "Attacchi",
        es: "Adjuntos",
        pl: "Attachment",
        uk: "Додатки",
        "zh-cn": "附录",
    },
    Attachments_JSON: {
        en: "Attachments JSON",
        de: "Anhänge JSON",
        ru: "Приспособления JSON",
        pt: "Anexos JSON",
        nl: "Aanklachten JSON",
        fr: "Attachements JSON",
        it: "Attacchi JSON",
        es: "Adjuntos JSON",
        pl: "Attachment JSON",
        uk: "Додатки JSON",
        "zh-cn": "附录 JSON",
    },
    "Cannot found password": {
        en: "Cannot found password! Restart Adapter please! - %s",
        de: "Passwort nicht gefunden! Neustart Adapter bitte! - %s",
        ru: "Не удалось найти пароль! Перезапустите адаптер, пожалуйста! - %s",
        pt: "Não encontrei senha! Reinicie o adaptador por favor! - %s",
        nl: "Kan geen wachtwoord vinden! Adapter, alsjeblieft! - %s",
        fr: "Je n'ai pas trouvé de mot de passe ! Adaptateur Restart s'il vous plaît! - %s",
        it: "Non è possibile trovare la password! Riavviare adattatore per favore! - %s",
        es: "¡No puedo encontrar contraseña! Adaptador de reinicio, por favor! - %s",
        pl: "Cannot odnalazł hasło. Restart Adapter (ang.)! - %s",
        uk: "Не знайдено пароля! Перезавантажити адаптер будь ласка! - %s",
        "zh-cn": "失败! Restart Adapter! - %s",
    },
    "decrypt pw": {
        en: "It is not possible to decrypt the password! Please restart the adapter! - %s",
        de: "Es ist nicht möglich, das Passwort zu entschlüsseln! Bitte starten Sie den Adapter neu! - %s",
        ru: "Невозможно расшифровать пароль! Пожалуйста, перезапустите адаптер! - %s",
        pt: "Não é possível descriptografar a senha! Por favor, reinicie o adaptador! - %s",
        nl: "Het is niet mogelijk om het wachtwoord te ontcijferen! Herstart de adapter! - %s",
        fr: "Il n'est pas possible de décrypter le mot de passe ! Veuillez redémarrer l'adaptateur ! - %s",
        it: "Non è possibile decifrare la password! Riavviare l'adattatore! - %s",
        es: "¡No es posible descifrar la contraseña! ¡Por favor reinicia el adaptador! - %s",
        pl: "Nie jest możliwe rozszyfrowanie hasła! Powracaj się do tyłu! - %s",
        uk: "Неможливо розшифрувати пароль! Будь ласка, перезапустіть адаптер! - %s",
        "zh-cn": "不能把言词加一! 请再接再厉! - %s",
    },
    "Restart Adapter": {
        en: "Memory MEMRSS %s above threshold %s Adapter is restarting.",
        de: "Speicher MEMRSS %s oberhalb der Schwelle %s Adapter wird neu gestartet.",
        ru: "Память MEMRSS %s над порогом %s Адаптер перезапускается.",
        pt: "Memória MEMRSS %s limiar acima %s O adaptador está a reiniciar.",
        nl: "Memory MeMRS %s drempel %s Adapter herstelt.",
        fr: "Memory MEMRSS %s au-dessus du seuil %s L'adaptateur redémarre.",
        it: "Memoria MEMRSS %s sopra la soglia %s L'adattatore sta riavviando.",
        es: "Memoria MEMRSS %s above threshold %s El adaptador está descansando.",
        pl: "Pamięć pamięci %s powyżej progu %s Adapter jest odwrócony.",
        uk: "Пам'яті MEMRSS %s над порігм %s Адаптер перезавантаження.",
        "zh-cn": "中小企业福利 %s 以上阈值 %s 道歉正在恢复。.",
    },
    "Restart Adapter Text": {
        en: "Threshold reached with %s MB.",
        de: "Schwellwert erreicht mit %s MB.",
        ru: "Threshold достиг %s МБ.",
        pt: "Threshold chegou com %s MB.",
        nl: "Drempel bereikt met %s MB.",
        fr: "Le seuil atteint %s Mo.",
        it: "Soglia raggiunta con %s MB.",
        es: "Umbral alcanzado con %s MB.",
        pl: "Threshold osiągnął wynik %s MB.",
        uk: "Досягнення з %s Мб.",
        "zh-cn": "至 %s 议 程.",
    },
    "Restart Adapter Header": {
        en: "Threshold",
        de: "Schwellwert",
        ru: "Порог",
        pt: "Limitação",
        nl: "Draad",
        fr: "Threshold",
        it: "Soglia",
        es: "Umbral",
        pl: "Threshold",
        uk: "Пороги",
        "zh-cn": "解雇",
    },
    "No threshold": {
        en: "Threshold with %s MB not reached.",
        de: "Schwellwert mit %s MB nicht erreicht.",
        ru: "Порог с %s МБ не достигнут.",
        pt: "Limite com %s MB não alcançado.",
        nl: "Dreigen met %s MB niet bereikt.",
        fr: "Le seuil de %s Mo n'est pas atteint.",
        it: "Soglia con %s MB non raggiunta.",
        es: "Umbral con %s MB no alcanzado.",
        pl: "Dotarł do niego %s MB.",
        uk: "Пороги з %s Мб не досягли.",
        "zh-cn": "暂不达 %s 个。.",
    },
    "Restart Adapter Text NO DP": {
        en: "No data point specified.",
        de: "Kein Datenpunkt angegeben.",
        ru: "Нет данных.",
        pt: "Nenhum ponto de dados especificado.",
        nl: "Geen gegevens gespecificeerd.",
        fr: "Aucun point de données spécifié.",
        it: "Nessun punto di dati specificato.",
        es: "No se especifica ningún punto de datos.",
        pl: "Nie ma określonego punktu danych.",
        uk: "Немає вказаної точки даних.",
        "zh-cn": "没有具体说明数据点。.",
    },
    "Adapter could not restart": {
        en: "Adapter could not restart - %s",
        de: "Adapter konnte nicht neu starten - %s",
        ru: "Адаптер не может перезапустить - %s",
        pt: "Adaptador não poderia reiniciar - %s",
        nl: "Adapter kon niet herstarten - %s",
        fr: "Adaptateur ne peut pas redémarrer - %s",
        it: "Adattatore non poteva riavviare - %s",
        es: "Adaptador no puede reiniciar - %s",
        pl: "Adapter nie mógł restartować - %s",
        uk: "Адаптер не може перезапустити - %s",
        "zh-cn": "道歉不能再恢复。 - %s",
    },
    Online_Counter: {
        en: "Online counter",
        de: "Online-Zähler",
        ru: "Онлайн счетчик",
        pt: "Contador online",
        nl: "Online count",
        fr: "Compteur en ligne",
        it: "Contatore online",
        es: "Contrato en línea",
        pl: "Strona internetowa",
        uk: "Онлайн лічильник",
        "zh-cn": "网上反击",
    },
    Online_History: {
        en: "Online connection history",
        de: "Online-Verbindungshistorie",
        ru: "История онлайн-соединения",
        pt: "História de conexão online",
        nl: "Online connectiegeschiedenis",
        fr: "Historique de connexion en ligne",
        it: "Storia della connessione online",
        es: "Historia de conexión en línea",
        pl: "Historia połączeń online",
        uk: "Історія підключення онлайн",
        "zh-cn": "在线联系历史。",
    },
    Closed: {
        en: "Closed",
        de: "Geschlossen",
        ru: "Закрыто",
        pt: "Fechado",
        nl: "Gesloten",
        fr: "Fermé",
        it: "Chiuso",
        es: "Cerrado",
        pl: "Closed",
        uk: "Закрити",
        "zh-cn": "闭门会议",
    },
    Online: {
        en: "Online",
        de: "Online",
        ru: "Онлайн",
        pt: "Online",
        nl: "Online",
        fr: "Online",
        it: "Online",
        es: "Online",
        pl: "Online",
        uk: "Інтернет",
        "zh-cn": "在线",
    },
    duplicate_icon: {
        en: "Duplicate icon name: %s",
        de: "Doppelter Iconname: %s",
        ru: "Дублирование иконки имя: %s",
        pt: "Duplicar o nome do ícone: %s",
        nl: "Duplicaat icon naam: %s",
        fr: "Nom d'icône double: %s",
        it: "Duplica il nome dell'icona: %s",
        es: "Nombre de icono duplicado: %s",
        pl: "Nazwisko ikon: %s",
        uk: "Дублікатний ім'я ікони: %s",
        "zh-cn": "双重名称。: %s",
    },
    duplicate_nodemailer: {
        en: "Duplicate Nodemailer name: %s",
        de: "Duplicate Nodemailer name: %s",
        ru: "Duplicate Nodemailer имя: %s",
        pt: "Nome Duplicate Nodemailer: %s",
        nl: "Duplicaat Nodemailer naam: %s",
        fr: "Duplicate Nodemailer nom: %s",
        it: "Duplicato nome Nodemailer: %s",
        es: "Duplicar nombre Nodemailer: %s",
        pl: "Nazwisko Nodemailer: %s",
        uk: "Дублікат Nodemailer name: %s",
        "zh-cn": "双重传真号码。: %s",
    },
    greater_than: {
        en: "Content greater than %s bytes",
        de: "Inhalt größer als %s Bytes",
        ru: "Содержание более %s байт",
        pt: "Conteúdo superior a %s bytes",
        nl: "Content groter dan %s bytes",
        fr: "Contenu supérieur à %s octets",
        it: "Contenuto superiore a %s byte",
        es: "Contenido superior a %s bytes",
        pl: "Znajdowało się tu ponad %s sztuk",
        uk: "Зміст більше %s байтів",
        "zh-cn": "第%s条",
    },
    max_mail: {
        en: "A maximum of 100 emails is possible.",
        de: "Maximal 100 E-Mails sind möglich.",
        ru: "Возможен максимум 100 писем.",
        pt: "Um máximo de 100 emails é possível.",
        nl: "Een maximum van 100 e-mails is mogelijk.",
        fr: "Un maximum de 100 courriels est possible.",
        it: "È possibile un massimo di 100 email.",
        es: "Es posible un máximo de 100 emails.",
        pl: "Możliwe jest maksymalnie 100 e-maili.",
        uk: "Можлива максимальна кількість 100 електронних листів.",
        "zh-cn": "可能有100个电子邮件。.",
    },
    "Missing fetch": {
        en: "Missing fetch",
        de: "Fehlende Fetch",
        ru: "Отсутствующий забор",
        pt: "Missing fetch",
        nl: "Vermist Fetch",
        fr: "Missing fetch",
        it: "Presa mancante",
        es: "Desaparecido",
        pl: "Missing fetch",
        uk: "М'ясо курча",
        "zh-cn": "失踪",
    },
};
